import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
CORE_PINE_PATH = REPO_ROOT / "tradingview" / "Signal_Strategy_Core[Glory].pine"
DISPLAY_PINE_PATH = REPO_ROOT / "tradingview" / "Signal_Strategy_Display[Glory].pine"


class TradingViewStrategyCorePineTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.source = CORE_PINE_PATH.read_text(encoding="utf-8")
        cls.display_source = DISPLAY_PINE_PATH.read_text(encoding="utf-8")

    def test_core_and_display_scripts_have_separate_responsibilities(self):
        core = self.source
        display = self.display_source

        self.assertIn('strategy(title="Signal Strategy Core[Glory]"', core)
        self.assertIn('indicator(title="Signal Strategy Display[Glory]"', display)
        self.assertIn("alert(", core)
        self.assertIn("strategy.entry", core)
        self.assertIn("strategy.exit", core)
        self.assertNotIn("label.new(", core)
        self.assertNotIn("plot(", core)
        self.assertNotIn("plotshape(", core)
        self.assertNotIn("table.", core)
        self.assertNotIn("line.", core)
        self.assertIn("label.new(", display)
        self.assertIn("plotshape(", display)
        self.assertIn("table.cell", display)
        self.assertNotIn("strategy.", display)
        self.assertNotIn("strategy(", display)
        self.assertNotIn("alert(", display)
        self.assertNotIn("basePayload", display)
        self.assertNotIn("jsonStr(", display)
        self.assertNotIn("jsonNum(", display)
        self.assertNotIn("jsonBool(", display)
        self.assertNotIn("mtfPayloadForDirection", display)
        self.assertNotIn("profitSpacePayload", display)

    def test_runner_uses_separate_activation_and_safety_tp(self):
        source = self.source

        self.assertIn('enableTpCheckpointRunner = input.bool(true, "Enable runner mode", group="05 Risk")', source)
        self.assertIn('runnerActivationR = input.float(1.0, "Runner activation (R)", step=0.25, minval=0.25, maxval=10.0, group="05 Risk")', source)
        self.assertIn('runnerSafetyR = input.float(4.0, "Runner safety TP (R)", step=0.5, minval=1.0, maxval=20.0, group="05 Risk")', source)
        self.assertIn("setupUsesRunner(string setup)", source)
        self.assertIn("calcRunnerActivationTarget(float entryPrice, float stopPrice, int direction)", source)
        self.assertIn("bool longRunnerCandidate = setupUsesRunner(longSetup) and not setupIsMr(longSetup)", source)
        self.assertIn("float longRunnerActivationRaw = setupUsesRunner(longSetup) and not setupIsMr(longSetup) ? calcRunnerActivationTarget(longEntryCandidate, longStopCandidate, 1) : na", source)
        self.assertIn("bool longRunnerCandidate = setupUsesRunner(longSetup) and not setupIsMr(longSetup) and longStructureTargetAvailable and not na(longRunnerActivationRaw) and longStructureTargetRaw > longRunnerActivationRaw and rewardRiskMultiple(structureRewardPerShare(1, longEntryCandidate, longStructureTargetRaw), structureRiskPerShare(1, longEntryCandidate, longStopCandidate)) >= runnerSafetyR", source)
        self.assertIn("float longRunnerActivationCandidate = longRunnerCandidate ? longRunnerActivationRaw : na", source)
        self.assertIn("float longTargetCandidate = longStructureTargetRaw", source)
        self.assertIn("bool shortRunnerCandidate = setupUsesRunner(shortSetup) and not setupIsMr(shortSetup)", source)
        self.assertIn("float shortRunnerActivationRaw = setupUsesRunner(shortSetup) and not setupIsMr(shortSetup) ? calcRunnerActivationTarget(shortEntryCandidate, shortStopCandidate, -1) : na", source)
        self.assertIn("bool shortRunnerCandidate = setupUsesRunner(shortSetup) and not setupIsMr(shortSetup) and shortStructureTargetAvailable and not na(shortRunnerActivationRaw) and shortStructureTargetRaw < shortRunnerActivationRaw and rewardRiskMultiple(structureRewardPerShare(-1, shortEntryCandidate, shortStructureTargetRaw), structureRiskPerShare(-1, shortEntryCandidate, shortStopCandidate)) >= runnerSafetyR", source)
        self.assertIn("float shortRunnerActivationCandidate = shortRunnerCandidate ? shortRunnerActivationRaw : na", source)
        self.assertIn("float shortTargetCandidate = shortStructureTargetRaw", source)
        self.assertIn("float runnerActivationPrice = longRunnerActivationCandidate", source)
        self.assertIn("float runnerActivationPrice = shortRunnerActivationCandidate", source)
        self.assertIn('strategy.exit("TV-L-RISK", from_entry="TV-L", stop=activeStop, limit=activeTarget', source)
        self.assertNotIn('comment_profit=', source)
        self.assertNotIn('comment_loss=', source)
        self.assertIn("exitTouchesTarget(int direction, float exitPrice, float targetPrice)", source)
        self.assertIn('exitReason := targetExit ? "take_profit" : stopExit ? "stop_loss" : exitReason', source)
        self.assertIn("activeRunnerActive := true", source)
        self.assertIn('if exitReason == "stop_loss" and activeRunnerActive and exitPnlPerShare > 0.0', source)
        self.assertIn('riskUpdateReason := "runner_activation"', source)
        self.assertIn('riskUpdateReason := riskUpdateReason == "" ? "runner_trail_stop" : riskUpdateReason', source)
        self.assertNotIn('riskUpdateReason := "tp_checkpoint_runner"', source)

        activation_index = source.index("if activeRunnerMode and not activeRunnerActive")
        trail_index = source.index("if activeRunnerMode and activeRunnerActive")
        alert_index = source.index("if riskChanged and enableAlerts")
        self.assertLess(activation_index, trail_index)
        self.assertLess(trail_index, alert_index)

    def test_payload_and_plots_distinguish_runner_activation_from_true_tp(self):
        source = self.source

        self.assertIn("jsonNum(\"take_profit\", targetPrice)", source)
        self.assertIn("jsonNum(\"target_checkpoint\", targetCheckpoint)", source)
        self.assertIn("jsonNum(\"safety_take_profit\", targetPrice)", source)
        self.assertIn("jsonNum(\"runner_activation_price\", runnerActivationPrice)", source)
        self.assertIn("jsonNum(\"runner_activation_r\", runnerActivationR)", source)
        self.assertIn("jsonBool(\"runner_enabled\", runnerMode)", source)
        self.assertIn("jsonBool(\"runner_active\", false)", source)
        self.assertIn("jsonBool(\"tp_checkpoint_runner\", runnerMode)", source)
        self.assertIn("jsonBool(\"target_is_hard\", not runnerMode)", source)
        self.assertIn("jsonBool(\"target_checkpoint_is_exit\", not runnerMode)", source)
        self.assertIn('jsonStr("target_role", mrSetup ? "mr_mean_tp" : runnerMode ? "structure_safety_tp" : "structure_hard_tp")', source)
        self.assertIn('jsonStr("mr_target_mode", mrSetup ? "mean_reversion_mixed" : "none")', source)
        self.assertIn('jsonNum("mr_mean_target_price", mrSetup ? targetPrice : na)', source)
        self.assertIn('jsonStr("mr_regime", mrRegimeValue)', source)
        self.assertIn('jsonBool("mr_regime_allowed", mrRegimeAllowedValue)', source)
        self.assertIn('jsonNum("mr_sd_slope_atr", sdSlopeAtr)', source)
        self.assertIn("buildEntryPayload(entryEventId, activeSignalId, activeTradeGroupId, posId, activePlanId, \"long\", longSetup, longReason, qty, longReferenceEntry, entryPrice, submittedLimitPrice", source)
        self.assertIn("buildEntryPayload(entryEventId, activeSignalId, activeTradeGroupId, posId, activePlanId, \"short\", shortSetup, shortReason, qty, shortReferenceEntry, entryPrice, submittedLimitPrice", source)
        self.assertIn("jsonRequestedSides(string requestedSides)", source)
        self.assertIn('string requestedSides = stopChanged and targetChanged ? "stop_loss,take_profit" : stopChanged ? "stop_loss" : targetChanged ? "take_profit" : ""', source)
        self.assertIn("float eventNewTarget = targetChanged ? activeTarget : na", source)
        self.assertNotIn('plot(', source)

    def test_exit_labels_show_pnl_amount_and_percent(self):
        core = self.source
        display = self.display_source

        self.assertNotIn("exitPnlLabelText(", core)
        self.assertIn("exitPnlLabelText(string reason, string timeText, float price, float pnl, float pnlPct)", display)
        self.assertIn('closeDirectionTag(int direction) =>', display)
        self.assertIn('direction == -1 ? "平空" : direction == 1 ? "平多" : "平仓"', display)
        self.assertIn('PnL " + fmtSignedMoney(pnl) + " (" + fmtSignedPct(pnlPct) + ")"', display)
        self.assertIn("decisionExitRText(float rValue)", display)

    def test_flow_label_backgrounds_are_configurably_transparent(self):
        source = self.display_source
        label_lines = [line for line in source.splitlines() if "label.new(" in line]

        self.assertIn(
            'flowLabelTransparency = input.int(30, "Flow label background transparency", minval=0, maxval=100, group="08 Display")',
            source,
        )
        self.assertIn("flowBaseColor(string state, string direction) =>", source)
        self.assertIn("color.new(flowBaseColor(state, direction), flowLabelTransparency)", source)
        self.assertIn("flowStatusColor(string state, string direction) =>", source)
        self.assertIn("color.new(flowBaseColor(state, direction), 0)", source)
        self.assertIn("color=color.new(color.orange, flowLabelTransparency)", source)
        self.assertIn('color statusColor = displayEnterLong ? flowStatusColor("entry", "long") : displayEnterShort ? flowStatusColor("entry", "short")', source)
        self.assertIn("color.new(color.green, flowLabelTransparency)", source)
        self.assertIn("color.new(color.red, flowLabelTransparency)", source)
        self.assertFalse(
            [line for line in label_lines if "color.new(" in line and ", 0)" in line],
            "flow labels should not use opaque inline label backgrounds",
        )

    def test_flow_labels_default_to_compact_tooltips(self):
        source = self.display_source
        label_lines = [line for line in source.splitlines() if "label.new(" in line]

        self.assertIn('labelDetailMode = input.string("compact_tooltip", "Flow label detail mode", options=["compact_tooltip", "full_labels", "off"], group="08 Display")', source)
        self.assertIn('bool flowLabelsVisible = showFlowLabels and labelDetailMode != "off"', source)
        self.assertIn('bool compactFlowLabelMode = labelDetailMode == "compact_tooltip"', source)
        self.assertIn("flowLabelText(string compactText, string detailText) =>", source)
        self.assertIn("compactFlowLabelMode ? compactText : detailText", source)
        self.assertIn("flowLabelTooltip(string detailText) =>", source)
        self.assertIn('compactFlowLabelMode ? detailText : ""', source)
        self.assertTrue(label_lines, "expected Pine labels to be present")
        self.assertTrue(
            all("tooltip=flowLabelTooltip(" in line for line in label_lines),
            "all flow labels should preserve full details in tooltips",
        )
        self.assertIn("decisionSetupTag(string setup) =>", source)
        self.assertIn("decisionRiskLine(float entryPrice, float stopPrice, float targetPrice, float rewardRisk, float targetAtrMultiple) =>", source)
        self.assertIn('direction == "short" ? "空" : "多"', source)
        self.assertIn("decisionBlockReason(string reason, string profitFailureReason) =>", source)
        self.assertIn('string lowerActivateDecisionText = dtpBearDominant ? "\\n方向裁决: DTP强空，SD下轨优先顺势空" : ""', source)
        self.assertIn('string lowerActivateCompactText = dtpBearDominant ? "候选 空·SD↓\\n顺势优先" : "候选 多·SD↓\\n等组件"', source)
        self.assertIn("flowLabelText(lowerActivateCompactText, lowerActivateDetailText)", source)
        self.assertIn('string upperActivateDecisionText = dtpBullDominant ? "\\n方向裁决: DTP强多，SD上轨优先顺势多" : ""', source)
        self.assertIn('string upperActivateCompactText = dtpBullDominant ? "候选 多·SD↑\\n顺势优先" : "候选 空·SD↑\\n等组件"', source)
        self.assertIn("flowLabelText(upperActivateCompactText, upperActivateDetailText)", source)
        self.assertIn("flowLabelText(prepareCompactText, prepareDetailText)", source)
        self.assertIn("flowLabelText(blockedCompactText, blockedDetailText)", source)
        self.assertIn("flowLabelText(longEntryCompactText, longEntryDetailText)", source)
        self.assertIn("flowLabelText(shortEntryCompactText, shortEntryDetailText)", source)
        self.assertIn('string prepareCompactText = "观察 " + decisionDirectionTag(candidateDirection) + "·" + decisionSetupTag(candidateSetup) + "\\n" + decisionComponentLine(candidateProgressText, candidateWaitText)', source)
        self.assertIn('string blockedCompactReasonText = decisionBlockReason(blockedReason, blockedProfitSpaceEntryBlocked ? blockedProfitSpaceFailureReason : "none")', source)
        self.assertIn('string blockedCompactMetricText = blockedProfitSpaceEntryBlocked ? " / " + decisionProfitMetricLine(blockedStructureRewardRisk, blockedTargetDistanceAtr) : ""', source)
        self.assertIn('string blockedCompactText = "过滤 " + decisionDirectionTag(blockedDirection) + "·" + decisionSetupTag(blockedSetup) + "\\n" + blockedCompactReasonText + blockedCompactMetricText', source)
        self.assertIn('string longEntryCompactText = "待触及 多·" + decisionSetupTag(longSetup) + " " + str.tostring(longEntryCandidate, "#.##") + "\\n" + decisionRiskLine(longEntryCandidate, longStopCandidate, longTargetCandidate, longStructureRewardRisk, longTargetDistanceAtr)', source)
        self.assertIn('string shortEntryCompactText = "待触及 空·" + decisionSetupTag(shortSetup) + " " + str.tostring(shortEntryCandidate, "#.##") + "\\n" + decisionRiskLine(shortEntryCandidate, shortStopCandidate, shortTargetCandidate, shortStructureRewardRisk, shortTargetDistanceAtr)', source)

    def test_fast_in_defaults_volatility_filter_and_marker_toggles(self):
        source = self.source
        display = self.display_source

        self.assertIn('positionAmount = input.float(5000, "Notional per trade ($)", step=500, minval=100, group="05 Risk")', source)
        self.assertIn('sdSignalBand = input.int(3, "MR trigger band", minval=1, maxval=4, group="03 SD Channel")', source)
        self.assertIn('useVolatilityFilter = input.bool(true, "Block low-volatility entries", group="05 Risk")', source)
        self.assertIn('minAtrPctForEntry = input.float(0.08, "Minimum ATR% for entry", step=0.01, minval=0.0, group="05 Risk")', source)
        self.assertIn("bool lowVolatilityEntryBlocked = useVolatilityFilter and atrPct < minAtrPctForEntry", source)
        self.assertIn('blockLongReason := "low_volatility"', source)
        self.assertIn('blockShortReason := "low_volatility"', source)
        self.assertIn('jsonBool("volatility_filter_enabled", useVolatilityFilter)', source)
        self.assertIn('jsonNum("min_atr_pct_for_entry", minAtrPctForEntry)', source)
        self.assertIn('jsonBool("volatility_entry_blocked", lowVolatilityEntryBlocked)', source)

        self.assertIn('showFractalMarkers = input.bool(true, "Show fractal markers", group="08 Display")', display)
        self.assertIn('showEmaCrossMarkers = input.bool(true, "Show EMA20/50 cross markers", group="08 Display")', display)
        self.assertIn('showSdHelperLines = input.bool(false, "Show SD regression/filter lines", group="08 Display")', display)
        self.assertIn("bool showSdHelperBandLines = showSdHelperLines or displayIndicatorMode or displayDebugMode", display)
        self.assertIn('plot(showBandLines ? sdSignalUpper : na, "SD signal upper"', display)
        self.assertIn('plot(showSdHelperBandLines ? sdReg : na, "SD regression"', display)
        self.assertIn('plot(showSdHelperBandLines ? sdFilterUpper : na, "SD filter upper"', display)
        self.assertIn('plotshape(showAnyFractalMarkers and fractalBull, "Fractal bull"', display)
        self.assertIn("offset=-fractalPeriod", display)
        self.assertIn('plotshape(showEmaCrossMarkers and emaGoldenCross, "EMA20/50 golden cross"', display)
        self.assertIn('plotshape(showEmaCrossMarkers and emaDeathCross, "EMA20/50 death cross"', display)
        self.assertIn('text="20/50金叉"', display)
        self.assertIn('text="20/50死叉"', display)

    def test_independent_two_leg_plan_metadata_and_per_leg_risk(self):
        source = self.source

        self.assertIn('strategy(title="Signal Strategy Core[Glory]", overlay=true, pyramiding=0', source)
        self.assertNotIn('max_labels_count', source)
        self.assertIn('scalePlanEnabled = input.bool(true, "Independent two-leg plan metadata", group="05 Risk")', source)
        self.assertIn('maxLegRisk = input.float(75.0, "Max loss per independent leg ($)", step=5.0, minval=1.0, group="05 Risk")', source)
        self.assertIn("float effectiveMaxLegRisk = scalePlanEnabled ? math.min(maxLegRisk, effectiveMaxPlanRisk / 2.0) : maxLossPerTrade", source)
        self.assertIn("scalePlanId(string direction, string setup) =>", source)
        self.assertIn('scalePlanEnabled ? planIdValue + "_leg1" : planIdValue', source)
        self.assertIn("scalePlanPayload(string planIdValue, string tradeGroupIdValue, int legIndex, string legTrigger) =>", source)
        self.assertIn('jsonStr("plan_type", "independent_two_leg")', source)
        self.assertIn('string resolvedPlanId = planIdValue == "" ? str.replace_all(tradeGroupIdValue, "_leg" + str.tostring(legIndex, "#"), "") : planIdValue', source)
        self.assertIn('jsonStr("plan_id", resolvedPlanId)', source)
        self.assertIn('jsonInt("leg_index", legIndex)', source)
        self.assertIn('jsonStr("leg_trade_group_id", tradeGroupIdValue)', source)
        self.assertIn('jsonNum("max_leg_notional", positionAmount)', source)
        self.assertIn('jsonNum("max_leg_risk", effectiveMaxLegRisk)', source)
        self.assertIn('jsonNum("max_plan_risk", effectiveMaxPlanRisk)', source)
        self.assertIn('jsonBool("independent_legs", true)', source)
        self.assertIn('jsonBool("cross_leg_protection_sync", false)', source)
        self.assertIn('jsonBool("aggregate_position_management", false)', source)
        self.assertIn('jsonStr("leg_order_mode", "independent_bracket")', source)
        self.assertIn('jsonBool("leg2_requires_leg1_protected", true)', source)
        self.assertIn("float longRiskStopCandidate = longQtyCandidate > 0.0 ? longEntryCandidate - effectiveMaxLegRisk / longQtyCandidate : longAtrStopCandidate", source)
        self.assertIn("float shortRiskStopCandidate = shortQtyCandidate > 0.0 ? shortEntryCandidate + effectiveMaxLegRisk / shortQtyCandidate : shortAtrStopCandidate", source)
        self.assertIn('string planIdValue = scalePlanId("long", longSetup)', source)
        self.assertIn('string planIdValue = scalePlanId("short", shortSetup)', source)
        self.assertIn("activePlanId := planIdValue", source)
        self.assertIn("scalePlanPayload(activePlanId, activeTradeGroupId, 1, activeEntryAnchorSource)", source)
        self.assertNotIn("pyramiding=2", source)

    def test_profit_space_filter_blocks_small_net_roi_or_target_space(self):
        source = self.source
        display = self.display_source

        self.assertIn('useProfitSpaceFilter = input.bool(true, "Block insufficient profit space", group="05 Risk")', source)
        self.assertIn('minNetProfitForEntry = input.float(50.0, "Minimum net profit ($)", step=5.0, minval=0.0, group="05 Risk")', source)
        self.assertIn('minNetRoiPctForEntry = input.float(1.0, "Minimum net ROI (%)", step=0.1, minval=0.0, group="05 Risk")', source)
        self.assertIn("float profitSpaceMinNetProfitFloor = 50.0", source)
        self.assertIn("float profitSpaceMinNetRoiPctFloor = 1.0", source)
        self.assertIn("float effectiveMinNetProfitForEntry = math.max(minNetProfitForEntry, profitSpaceMinNetProfitFloor)", source)
        self.assertIn("float effectiveMinNetRoiPctForEntry = math.max(minNetRoiPctForEntry, profitSpaceMinNetRoiPctFloor)", source)
        self.assertIn('maxCostPctOfReward = input.float(15.0, "Maximum cost / reward (%)", step=1.0, minval=0.0, group="05 Risk")', source)
        self.assertIn('minTargetAtrMultipleForEntry = input.float(1.0, "Minimum target distance (x ATR)", step=0.25, minval=0.0, group="05 Risk")', source)
        self.assertIn('minStructureRewardRiskForEntry = input.float(1.5, "Minimum structure reward/risk", step=0.1, minval=0.1, group="05 Risk")', source)
        self.assertIn('minWeakTrendRewardRiskForEntry = input.float(2.0, "Minimum weak/low-vol structure R/R", step=0.1, minval=0.1, group="05 Risk")', source)
        self.assertIn('weakTrendAtrPctMultiplier = input.float(1.25, "Weak/low-vol ATR% threshold multiplier"', source)
        self.assertIn('not structureStopAvailable ? "structure_stop_unavailable"', source)
        self.assertIn('not structureTargetAvailable ? "structure_target_unavailable"', source)
        self.assertIn('netProfit < effectiveMinNetProfitForEntry ? "net_profit_below_min"', source)
        self.assertIn('netRoiPct < effectiveMinNetRoiPctForEntry ? "net_roi_below_min"', source)
        self.assertIn('na(rewardRisk) or rewardRisk < minRewardRisk ? "reward_risk_below_min"', source)
        self.assertIn("profitSpaceEntryAllowed(float netProfit, float netRoiPct, float costPct, float targetAtrMultiple, float rewardRisk, bool structureStopAvailable, bool structureTargetAvailable, float minRewardRisk)", source)
        self.assertIn('blockLongReason := "profit_space_too_small"', source)
        self.assertIn('blockShortReason := "profit_space_too_small"', source)
        self.assertIn('reason == "profit_space_too_small" ? "等更大空间"', display)
        self.assertIn('"结构TP口径 预计净利 " + fmtSignedMoney(netProfit) + " / 占用ROI " + fmtSignedPct(netRoiPct) + " / 成本/毛利 "', display)
        self.assertIn("profitSpaceCheckpointText(bool runnerMode, float netProfit, float costPct, float targetAtrMultiple)", display)
        self.assertIn('"门槛 净利 >= " + fmtMoney(effectiveMinNetProfitForEntry)', display)
        self.assertIn('" / 占用ROI >= " + str.tostring(effectiveMinNetRoiPctForEntry', display)
        self.assertIn('成本/毛利 <= " + str.tostring(maxCostPctOfReward', display)
        self.assertIn('R >= " + str.tostring(minRewardRisk', display)
        self.assertIn('TP >= " + str.tostring(minTargetAtrMultipleForEntry', display)
        self.assertIn("profitSpaceNetProfitCompareText(float netProfit)", display)
        self.assertIn('"净利 " + fmtSignedMoney(netProfit) + operatorText + fmtMoney(effectiveMinNetProfitForEntry) + gapText', display)
        self.assertIn('netProfit < effectiveMinNetProfitForEntry ? "，差 " + fmtMoney(effectiveMinNetProfitForEntry - netProfit)', display)
        self.assertIn("profitSpaceNetRoiCompareText(float netRoiPct)", display)
        self.assertIn("profitSpaceCostCompareText(float costPct)", display)
        self.assertIn("profitSpaceRewardRiskCompareText(float rewardRisk, float minRewardRisk)", display)
        self.assertIn("profitSpaceTargetAtrCompareText(float targetAtrMultiple)", display)
        self.assertIn('"\\n获利空间不足\\n" + profitSpaceNetProfitCompareText(netProfit)', display)
        self.assertIn('profitSpaceBlockedStatusText(float netProfit, float netRoiPct, float costPct, float targetAtrMultiple, float rewardRisk, float minRewardRisk)', display)
        self.assertIn('profitSpacePayload(direction, qty, entryPrice, stopPrice, targetPrice, targetCheckpoint)', source)
        self.assertIn("float longExpectedGrossProfit = profitSpaceGrossProfit(1, longEntryCandidate, longTargetCandidate, longQtyCandidate)", source)
        self.assertIn("float shortExpectedGrossProfit = profitSpaceGrossProfit(-1, shortEntryCandidate, shortTargetCandidate, shortQtyCandidate)", source)
        self.assertIn("float longCheckpointGrossProfit = profitSpaceGrossProfit(1, longEntryCandidate, longProfitCheckpoint, longQtyCandidate)", source)
        self.assertIn("float shortCheckpointGrossProfit = profitSpaceGrossProfit(-1, shortEntryCandidate, shortProfitCheckpoint, shortQtyCandidate)", source)
        self.assertIn("float grossProfitValue = profitSpaceGrossProfit(directionSign, entryPrice, targetPrice, qty)", source)
        self.assertIn("float checkpointGrossProfitValue = profitSpaceGrossProfit(directionSign, entryPrice, targetCheckpoint, qty)", source)
        self.assertIn('jsonNum("entry_notional", entryNotionalValue)', source)
        self.assertIn('jsonStr("profit_space_basis", "final_structure_target")', source)
        self.assertIn('jsonNum("expected_net_profit", netProfitValue)', source)
        self.assertIn('jsonNum("expected_net_roi_pct", netRoiPctValue)', source)
        self.assertIn('jsonNum("cost_pct_of_reward", costPctValue)', source)
        self.assertIn('jsonNum("profit_space_checkpoint_price", targetCheckpoint)', source)
        self.assertIn('jsonNum("checkpoint_gross_profit", checkpointGrossProfitValue)', source)
        self.assertIn('jsonNum("checkpoint_net_profit", checkpointNetProfitValue)', source)
        self.assertIn('jsonNum("checkpoint_target_distance_atr", checkpointTargetAtrValue)', source)
        self.assertIn('jsonNum("structure_reward_risk", structureRewardRiskValue)', source)
        self.assertIn('jsonNum("net_reward_risk", netRewardRiskValue)', source)
        self.assertIn('jsonNum("target_distance_atr", targetAtrValue)', source)
        self.assertIn('jsonBool("profit_space_entry_allowed", entryAllowedValue)', source)
        self.assertIn('jsonNum("min_net_profit_for_entry", effectiveMinNetProfitForEntry)', source)
        self.assertIn('jsonNum("min_net_roi_pct_for_entry", effectiveMinNetRoiPctForEntry)', source)
        self.assertIn('jsonNum("min_structure_reward_risk_for_entry", minRewardRiskValue)', source)
        self.assertNotIn("float longExpectedGrossProfit = profitSpaceGrossProfit(1, longEntryCandidate, longProfitCheckpoint, longQtyCandidate)", source)
        self.assertNotIn("float shortExpectedGrossProfit = profitSpaceGrossProfit(-1, shortEntryCandidate, shortProfitCheckpoint, shortQtyCandidate)", source)

    def test_entry_windows_are_continuous_layered_and_serialized(self):
        source = self.source
        display = self.display_source

        self.assertIn('string ENTRY_WINDOW_MODEL = "continuous_layered_v1"', source)
        self.assertIn("int ENTRY_PRIMARY_START_MIN = 9 * 60 + 45", source)
        self.assertIn("int ENTRY_PRIMARY_END_MIN = 11 * 60 + 30", source)
        self.assertIn("int ENTRY_CLOSING_START_MIN = 14 * 60", source)
        self.assertIn("int ENTRY_CUTOFF_MIN = 15 * 60 + 15", source)
        self.assertIn('tradingSession = input.session("0945-1530", "Trading session", group="07 TV Primary Events")', source)
        self.assertIn('entrySession = input.session("0945-1515", "Continuous entry window", group="07 TV Primary Events")', source)
        self.assertIn('primaryEntrySession = input.session("0945-1130", "Primary entry layer", group="07 TV Primary Events")', source)
        self.assertIn('qualityEntrySession = input.session("1130-1400", "Quality entry layer", group="07 TV Primary Events")', source)
        self.assertIn('closingQualityEntrySession = input.session("1400-1515", "Closing quality entry layer", group="07 TV Primary Events")', source)
        self.assertIn('int entryCloseEtMinutes = hour(time_close, "America/New_York") * 60 + minute(time_close, "America/New_York")', source)
        self.assertIn("bool inContinuousEntryCloseWindow = entryCloseEtMinutes >= ENTRY_PRIMARY_START_MIN and entryCloseEtMinutes <= ENTRY_CUTOFF_MIN", source)
        self.assertIn("bool inContinuousEntryWindow = not na(time(timeframe.period, entrySession, syminfo.timezone)) and inContinuousEntryCloseWindow", source)
        self.assertIn("bool inEntryWindow = not useIntradayEntryWindows or inContinuousEntryWindow", source)
        self.assertIn('string entryWindowStage = not useIntradayEntryWindows ? "disabled" : inPrimaryEntryWindow ? "primary" : inQualityEntryWindow ? "quality" : inClosingQualityEntryWindow ? "closing_quality" : "no_new_entry"', source)
        self.assertIn('bool lateQualityEntryWindow = entryWindowStage == "quality" or entryWindowStage == "closing_quality"', source)
        self.assertIn("entryWindowDiagnosticsText() =>", display)
        self.assertIn('"窗口: " + entryWindowStage + " / " + ENTRY_WINDOW_MODEL', display)
        self.assertIn('lateQualityEntryWindow ? minWeakTrendRewardRiskForEntry : minStructureRewardRiskForEntry', source)
        self.assertIn('jsonStr("entry_window_model", ENTRY_WINDOW_MODEL)', source)
        self.assertIn('jsonStr("entry_window_stage", entryWindowStage)', source)
        self.assertIn('jsonStr("entry_cutoff_time", "15:15")', source)
        self.assertIn("bool pendingEntryWindowExpired = confirmed and activePendingEntry and strategy.position_size == 0 and not inEntryWindow", source)
        self.assertIn("不在09:45-15:15连续入场窗口，新仓等待下一交易日/下一窗口", display)
        self.assertNotIn("morningEntrySession", source)
        self.assertNotIn("afternoonEntrySession", source)
        self.assertNotIn("Morning entry window", source)
        self.assertNotIn("Afternoon entry window", source)

    def test_structure_first_tp_sl_uses_atr_only_as_buffer_and_filter(self):
        source = self.source

        self.assertIn('string TP_SL_MODEL = "structure_first_atr_buffer_v1"', source)
        self.assertIn("validResistanceLevel(float referencePrice, float levelPrice)", source)
        self.assertIn("validSupportLevel(float referencePrice, float levelPrice)", source)
        self.assertIn("structureRewardPerShare(int direction, float entryPrice, float targetPrice)", source)
        self.assertIn("structureRiskPerShare(int direction, float entryPrice, float stopPrice)", source)
        self.assertIn("rewardRiskMultiple(float rewardPerShare, float riskPerShare)", source)
        self.assertIn("float longStopSupportBase = nearestSupportBelow(longEntryCandidate", source)
        self.assertIn("float longStructureStopCandidate = longStructureStopAvailable ? longStopSupportBase - atrRaw * structuralSlBufferAtr : longAtrStopCandidate", source)
        self.assertIn("float longStopCandidate = math.max(longStructureStopCandidate, longRiskStopCandidate)", source)
        self.assertIn("float shortStopResistanceBase = nearestResistanceAbove(shortEntryCandidate", source)
        self.assertIn("float shortStructureStopCandidate = shortStructureStopAvailable ? shortStopResistanceBase + atrRaw * structuralSlBufferAtr : shortAtrStopCandidate", source)
        self.assertIn("float shortStopCandidate = math.min(shortStructureStopCandidate, shortRiskStopCandidate)", source)
        self.assertIn("float longTrendStructureTargetRaw = nearestResistanceAbove(longEntryCandidate", source)
        self.assertIn("float shortTrendStructureTargetRaw = nearestSupportBelow(shortEntryCandidate", source)
        self.assertIn("float longTargetCandidate = longStructureTargetRaw", source)
        self.assertIn("float shortTargetCandidate = shortStructureTargetRaw", source)
        self.assertIn('jsonStr("tp_sl_model", TP_SL_MODEL)', source)
        self.assertIn('jsonStr("atr_role", "buffer_and_filter_only")', source)
        self.assertIn('jsonStr("rr_basis", "structure_stop_to_structure_target")', source)
        self.assertIn('jsonBool("target_is_structure", structureTargetAvailable)', source)
        self.assertIn('jsonNum("structure_stop_loss", stopPrice)', source)
        self.assertIn('jsonNum("structure_take_profit", targetPrice)', source)
        self.assertIn('jsonNum("reward_risk", structureRewardRiskValue)', source)
        self.assertNotIn('jsonNum("reward_risk", rrRatio)', source)

    def test_window_activation_pre_alert_is_non_directional(self):
        source = self.source
        prealert_start = source.index("buildPreAlertPayload")
        prealert_end = source.index("// TV-primary event flow")
        prealert_section = source[prealert_start:prealert_end]

        self.assertIn("buildPreAlertPayload(string eventIdValue, string pendingPositionId, string activationWindow)", source)
        self.assertIn('jsonStr("pre_alert_stage", "window_activation")', prealert_section)
        self.assertIn('jsonStr("activation_window", activationWindow)', prealert_section)
        self.assertIn('jsonNum("activation_window_upper", sdSignalUpper)', prealert_section)
        self.assertIn('jsonNum("activation_window_lower", sdSignalLower)', prealert_section)
        self.assertIn('jsonBool("entry_decides_direction", true)', prealert_section)
        self.assertNotIn("direction_bias", prealert_section)
        self.assertNotIn("candidate_direction", prealert_section)
        self.assertNotIn("position_side", prealert_section)
        self.assertNotIn("mtfPayloadForDirection(candidateDirection)", prealert_section)
        self.assertNotIn("if enableAlerts and preAlertCross", source)
        self.assertIn("var bool candidateNoticeSentToday = false", source)
        self.assertIn("if isNewTradingDay\n    candidateNoticeSentToday := false", source)
        self.assertIn("bool lowerCandidateNotice = lowerActivationEvent and not candidateNoticeSentToday", source)
        self.assertIn("bool upperCandidateNotice = upperActivationEvent and not candidateNoticeSentToday and not lowerCandidateNotice", source)
        self.assertIn("if lowerCandidateNotice or upperCandidateNotice\n    candidateNoticeSentToday := true", source)
        self.assertNotIn("if enableAlerts and canTrade and flatForEntry and lowerActivationEvent", source)
        self.assertNotIn("if enableAlerts and canTrade and flatForEntry and upperActivationEvent", source)
        self.assertNotIn("pendingObservationWindow", source)
        self.assertNotIn("观察池入选", source)
        self.assertNotIn("PRE_ALERT 入池候选", source)
        self.assertIn('alert(buildPreAlertPayload(eventId("pre_alert", "window_lower"), pendingLowerId, "lower"), alert.freq_all)', source)
        self.assertIn('alert(buildPreAlertPayload(eventId("pre_alert", "window_upper"), pendingUpperId, "upper"), alert.freq_all)', source)

    def test_activation_labels_mark_observe_pool_not_entry(self):
        source = self.display_source
        activation_lines = "\n".join(
            line
            for line in source.splitlines()
            if line.strip().startswith("label.new") and (
                'flowLabelColor("activate_lower"' in line or 'flowLabelColor("activate_upper"' in line
            )
        )

        self.assertIn('"已入选候选池\\n" + syminfo.ticker + " · SD窗口开启\\nSD下轨候选\\n非开仓点，等组件"', source)
        self.assertIn('"已入选候选池\\n" + syminfo.ticker + " · SD窗口开启\\nSD上轨候选\\n非开仓点，等组件"', source)
        self.assertIn("if flowLabelsVisible and lowerActivationEvent", source)
        self.assertIn("if flowLabelsVisible and upperActivationEvent", source)
        self.assertNotIn("BUY", activation_lines)
        self.assertNotIn("entry", activation_lines)
        self.assertNotIn("买入做多", activation_lines)
        self.assertNotIn("卖出做空", activation_lines)

    def test_signal_diagnostics_draw_filtered_candidates_without_alerts(self):
        source = self.display_source
        diagnostic_start = source.index("bool diagnosticLongCandidate")
        diagnostic_end = source.index("if flowLabelsVisible and displayEnterLong")
        diagnostic_section = source[diagnostic_start:diagnostic_end]

        self.assertIn('showSignalDiagnostics = input.bool(true, "Show raw/filtered signal diagnostics", group="08 Display")', source)
        self.assertIn("bool diagnosticLongCandidate = canTrade and allowLong and longRaw and not displayEnterLong", source)
        self.assertIn("bool diagnosticShortCandidate = canTrade and allowShort and shortRaw and not displayEnterShort", source)
        self.assertIn("bool blockedNow = diagnosticLongCandidate or diagnosticShortCandidate", source)
        self.assertIn("if flowLabelsVisible and showSignalDiagnostics and blockedNow and blockedVisualKey != lastBlockVisualKey", source)
        self.assertIn('string blockedReason = blockedReasonRaw == "" ? "candidate_filtered" : blockedReasonRaw', source)
        self.assertIn('"信号过滤\\n" + directionDisplayName(blockedDirection)', source)
        self.assertIn('"\\n主因: " + filterDisplayName(blockedReason)', source)
        self.assertIn('reason == "candidate_filtered" ? "候选未执行"', source)
        self.assertIn('reason == "candidate_filtered" ? "候选未进入下单分支，检查窗口/方向/数量条件"', source)
        self.assertIn("bool blockedProfitSpaceEntryBlocked = blockedDirection == \"long\" ? longProfitSpaceEntryBlocked : shortProfitSpaceEntryBlocked", source)
        self.assertIn("string blockedProfitSpaceFailureReason = blockedDirection == \"long\" ? profitSpaceFailureReason", source)
        self.assertIn("string blockedProfitText = blockedDirection == \"long\" ? profitSpaceSummaryText", source)
        self.assertIn("string blockedProfitSecondaryReason = blockedProfitSpaceEntryBlocked ? profitFailureDisplayName(blockedProfitSpaceFailureReason) : \"\"", source)
        self.assertIn('string blockedSecondaryText = blockedProfitSecondaryReason != "" and blockedReason != "profit_space_too_small" and blockedReason != "mr_target_space_too_small" ? "\\n次因: " + blockedProfitSecondaryReason : ""', source)
        self.assertIn('"\\n" + entryWindowDiagnosticsText() + "\\n组件: " + blockedComponentText', source)
        self.assertIn('string blockedCompactReasonText = decisionBlockReason(blockedReason, blockedProfitSpaceEntryBlocked ? blockedProfitSpaceFailureReason : "none")', source)
        self.assertIn('string blockedCompactText = "过滤 " + decisionDirectionTag(blockedDirection) + "·" + decisionSetupTag(blockedSetup) + "\\n" + blockedCompactReasonText + blockedCompactMetricText', source)
        self.assertIn("label.new(bar_index, blockedY, flowLabelText(blockedCompactText, blockedDetailText)", source)
        self.assertIn("string blockedVisualKey = blockedDirection + \":\" + blockedSetup + \":\" + blockedReason + \":\" + blockedComponentText", source)
        self.assertIn("mtfStatusForDirection(blockedDirection)", source)
        self.assertIn("blockedProfitSpaceEntryBlocked ? blockedProfitSpaceFailureReason : \"none\"", source)
        self.assertNotIn("alert(", diagnostic_section)

    def test_sd_window_resets_only_on_activation_events(self):
        source = self.source

        self.assertIn("bool lowerActivationEvent = canOpenEntry and sdLowerHit and (not lowerWindowActive or lowerWindowUsed or lowerWindowExpired or na(lowerWindowStart))", source)
        self.assertIn("bool upperActivationEvent = canOpenEntry and sdUpperHit and (not upperWindowActive or upperWindowUsed or upperWindowExpired or na(upperWindowStart))", source)
        self.assertIn("if lowerActivationEvent\n    lowerWindowActive := true", source)
        self.assertIn("if upperActivationEvent\n    upperWindowActive := true", source)
        self.assertNotIn("if sdLowerHit\n    lowerWindowActive := true", source)
        self.assertNotIn("if sdUpperHit\n    upperWindowActive := true", source)

    def test_entry_logic_requires_window_and_two_of_three_direction_components(self):
        source = self.source
        display = self.display_source

        self.assertIn("directionComponentCount(bool fractalReady, bool divReady, bool emaCrossReady)", source)
        self.assertIn('trendReactionZoneAtr = input.float(0.20, "Trend reaction zone (x ATR)"', source)
        self.assertIn('trendQuickRejectBars = input.int(3, "Trend quick rejection bars"', source)
        self.assertIn('trendLingerBars = input.int(6, "Trend support/resistance linger bars"', source)
        self.assertIn('trendBreakBufferAtr = input.float(0.05, "Trend range break buffer (x ATR)"', source)
        self.assertIn("int longTrendUpperDirectionComponents = directionComponentCount(trendBullFractalFresh, bullDivFresh, trendBullEmaCrossFresh)", source)
        self.assertIn("int longMrLowerRawDirectionComponents = directionComponentCount(lowerBullFractalSeen, bullDivSeen, lowerBullEmaCrossSeen)", source)
        self.assertIn("int longMrLowerDirectionComponents = directionComponentCount(lowerBullFractalFresh, bullDivFresh, lowerBullEmaCrossFresh)", source)
        self.assertIn("int shortMrUpperRawDirectionComponents = directionComponentCount(upperBearFractalSeen, bearDivSeen, upperBearEmaCrossSeen)", source)
        self.assertIn("int shortMrUpperDirectionComponents = directionComponentCount(upperBearFractalFresh, bearDivFresh, upperBearEmaCrossFresh)", source)
        self.assertIn("int shortTrendLowerDirectionComponents = directionComponentCount(trendBearFractalFresh, bearDivFresh, trendBearEmaCrossFresh)", source)
        self.assertIn("pullbackNearSupport(float barLow, float barClose, float levelPrice, float atrValue)", source)
        self.assertIn("pullbackNearResistance(float barHigh, float barClose, float levelPrice, float atrValue)", source)
        self.assertIn("var bool trendBullFractalSeen = false", source)
        self.assertIn("var bool trendBullEmaCrossSeen = false", source)
        self.assertIn("float recentHigh = ta.highest(high[1], entryLevelLookbackBars)", source)
        self.assertIn('upperBullPullbackLineNow := pullbackNearSupport(low, close, emaFast, atrRaw) ? appendSource(upperBullPullbackLineNow, "pullback_ema20") : upperBullPullbackLineNow', source)
        self.assertIn('upperBullPullbackLineNow := pullbackNearSupport(low, close, recentLow, atrRaw) ? appendSource(upperBullPullbackLineNow, "pullback_recent_low") : upperBullPullbackLineNow', source)
        self.assertIn('lowerBearPullbackLineNow := pullbackNearResistance(high, close, emaFast, atrRaw) ? appendSource(lowerBearPullbackLineNow, "pullback_ema20") : lowerBearPullbackLineNow', source)
        self.assertIn('lowerBearPullbackLineNow := pullbackNearResistance(high, close, recentHigh, atrRaw) ? appendSource(lowerBearPullbackLineNow, "pullback_recent_high") : lowerBearPullbackLineNow', source)
        self.assertNotIn("pullback_signal_mid", source)
        self.assertIn("bool lowerBearPullbackNow = confirmed and (lowerWindowValid or bearTrendContinuationContext) and lowerBearPullbackLineNow != \"\"", source)
        self.assertIn("bool lowerBearPullbackFresh = lowerBearPullbackSeen and componentFresh(lowerBearPullbackBar)", source)
        self.assertIn("bool lowerBearContinuationFresh = lowerBearContinuationSeen and componentFresh(lowerBearContinuationBar)", source)
        self.assertIn("bool lowerBearTrendTriggerFresh = lowerBearTouchFresh or lowerBearPullbackFresh or lowerBearContinuationFresh", source)
        self.assertIn("bool lowerBearTrendTriggerSeen = lowerBearTouchSeen or lowerBearPullbackSeen or lowerBearContinuationSeen", source)
        self.assertIn('bool dtpBullDominant = dtpDir == 1 and (dtpPhase == "early" or dtpPhase == "confirmed" or dtpPhase == "mature")', source)
        self.assertIn('bool dtpBearDominant = dtpDir == -1 and (dtpPhase == "early" or dtpPhase == "confirmed" or dtpPhase == "mature")', source)
        self.assertIn('bool dtpWeakeningOrNeutral = dtpPhase == "weakening" or dtpDir == 0', source)
        self.assertIn("bool bullTrendContinuationContext = dtpBullDominant and emaFast >= emaSlow and close >= emaSlow and close >= sdReg and not mtfLongBlock", source)
        self.assertIn("bool bearTrendContinuationContext = dtpBearDominant and emaFast <= emaSlow and close <= emaSlow and close <= sdReg and not mtfShortBlock", source)
        self.assertIn("bool trendLongSupportLingerWait = bullTrendContinuationContext and not na(trendLongSupportTouchStart) and trendLongSupportTouchBars >= trendLingerBars and not trendLongRangeBreakoutNow", source)
        self.assertIn("bool trendShortResistanceLingerWait = bearTrendContinuationContext and not na(trendShortResistanceTouchStart) and trendShortResistanceTouchBars >= trendLingerBars and not trendShortRangeBreakdownNow", source)
        self.assertIn("bool upperBullContinuationNow = confirmed and bullTrendContinuationContext and not trendLongSupportLingerWait and upperBullContinuationLineNow != \"\"", source)
        self.assertIn("bool lowerBearContinuationNow = confirmed and bearTrendContinuationContext and not trendShortResistanceLingerWait and lowerBearContinuationLineNow != \"\"", source)
        self.assertIn("bool longTrendContextReady = (upperWindowValid or bullTrendContinuationContext) and not trendLongSupportLingerWait", source)
        self.assertIn("bool shortTrendContextReady = (lowerWindowValid or bearTrendContinuationContext) and not trendShortResistanceLingerWait", source)
        self.assertIn("var bool upperBullContinuationSeen = false", source)
        self.assertIn("bool upperBullContinuationFresh = upperBullContinuationSeen and componentFresh(upperBullContinuationBar)", source)
        self.assertIn("bool upperBullTrendTriggerFresh = upperBullTouchFresh or upperBullContinuationFresh", source)
        self.assertIn("bool setupLongTrendUpper = longTrendContextReady and upperBullTrendTriggerFresh and longTrendUpperDirectionComponents >= 2 and longTrendUpperStructureOk", source)
        self.assertIn("bool setupLongMrLower = lowerMrWindowValid and longMrLowerDirectionComponents >= 2", source)
        self.assertIn("bool setupShortMrUpper = upperMrWindowValid and shortMrUpperDirectionComponents >= 2 and (not dtpBullDominant or bearishReversalContext)", source)
        self.assertIn("bool setupShortTrendLowerTouch = shortTrendContextReady and lowerBearTouchFresh and shortTrendLowerDirectionComponents >= 2 and shortTrendLowerStructureOk", source)
        self.assertIn("bool setupShortTrendLowerPullback = shortTrendContextReady and lowerBearPullbackFresh and shortTrendLowerDirectionComponents >= 2 and shortTrendLowerStructureOk", source)
        self.assertIn("bool setupShortTrendLowerContinuation = bearTrendContinuationContext and not trendShortResistanceLingerWait and lowerBearContinuationFresh and shortTrendLowerDirectionComponents >= 2 and shortTrendLowerStructureOk", source)
        self.assertIn("bool setupShortTrendLower = setupShortTrendLowerTouch or setupShortTrendLowerPullback or setupShortTrendLowerContinuation", source)
        self.assertIn('setupShortTrendLowerContinuation ? "DTP bearish trend-continuation short: resistance rejection/range break + 2 of 3 bear direction components"', source)
        self.assertIn('setupShortTrendLowerPullback ? "SD lower trend-continuation short: pullback resistance + 2 of 3 bear direction components"', source)
        self.assertIn("int scoreLongTrendUpper = math.min(100,", source)
        self.assertIn("(longTrendContextReady ? 20 : 0) + (upperBullTrendTriggerSeen ? 30 : 0)", source)
        self.assertIn("int scoreLongMrLower = math.min(100,", source)
        self.assertIn("int scoreShortMrUpper = dtpBullDominant and not bearishReversalContext ? 0 : math.min(100,", source)
        self.assertIn("int scoreShortTrendLower = math.min(100, (shortTrendContextReady ? 25 : 0) + (lowerBearTrendTriggerSeen ? 25 : 0)", source)
        self.assertIn('missingComponents := trendLongSupportLingerWait ? appendSource(missingComponents, "key_level_wait") : missingComponents', source)
        self.assertIn('missingComponents := trendShortResistanceLingerWait ? appendSource(missingComponents, "key_level_wait") : missingComponents', source)
        self.assertIn('missingText := str.replace_all(missingText, "key_level_wait", "关键位突破")', display)
        self.assertIn('jsonBool("bull_fractal_seen", lowerBullFractalSeen or upperBullFractalSeen or trendBullFractalSeen)', source)
        self.assertIn('jsonBool("bull_ema_cross_seen", lowerBullEmaCrossSeen or upperBullEmaCrossSeen or trendBullEmaCrossSeen)', source)
        self.assertIn('string candidateDirectionDecisionText = bullTrendContinuationContext and candidateSetup == "trend_sdUpper" ? "\\n方向裁决: DTP强多，SD上轨优先顺势多" : bearTrendContinuationContext and candidateSetup == "trend_sdLower" ? "\\n方向裁决: DTP强空，SD下轨优先顺势空" : ""', display)
        self.assertIn('missingComponents := not lowerBearTrendTriggerSeen ? appendSource(missingComponents, "ema_bear_touch") : missingComponents', source)
        self.assertIn('missingText := str.replace_all(missingText, "ema_bear_touch", "空EMA/回抽")', display)

    def test_ema_death_continuation_short_without_upper_memory(self):
        source = self.source
        display = self.display_source

        self.assertIn('setup == "trend_emaDeathContinuation" ? "EMA死叉顺势空"', display)
        self.assertIn('setup == "trend_emaDeathContinuation" ? "弱势结构"', display)
        self.assertIn('missingText := str.replace_all(missingText, "weak_structure", "弱势结构")', display)
        self.assertIn("var bool trendBearFractalSeen = false", source)
        self.assertIn("var bool trendBearEmaCrossSeen = false", source)
        self.assertIn("var bool emaDeathContinuationShortUsed = false", source)
        self.assertIn("if fractalBear\n    trendBearFractalSeen := true", source)
        self.assertIn("if emaDeathCross\n    trendBearEmaCrossSeen := true", source)
        self.assertIn("emaDeathContinuationShortUsed := false", source)
        self.assertIn("bool trendBearFractalFresh = trendBearFractalSeen and componentFresh(trendBearFractalBar)", source)
        self.assertIn("bool trendBearEmaCrossFresh = trendBearEmaCrossSeen and componentFresh(trendBearEmaCrossBar)", source)
        self.assertIn("int shortEmaDeathContinuationDirectionComponents = directionComponentCount(trendBearFractalFresh, bearDivFresh, trendBearEmaCrossFresh)", source)
        self.assertIn("bool shortEmaDeathContinuationStructureOk = emaFast < emaSlow and close < emaSlow and close < sdReg", source)
        self.assertIn("bool setupShortEmaDeathContinuation = not emaDeathContinuationShortUsed and not setupShortPostUpperBreakdown and shortEmaDeathContinuationStructureOk and (not dtpBullDominant or bearishReversalContext) and trendBearEmaCrossFresh and (trendBearFractalFresh or bearDivFresh) and shortEmaDeathContinuationDirectionComponents >= 2", source)
        self.assertIn("bool shortSignalCandidate = setupShortPostUpperBreakdown or setupShortEmaDeathContinuation or setupShortMrUpper or setupShortTrendLower", source)
        self.assertIn('string shortSetup = setupShortPostUpperBreakdown ? "trend_sdUpperBreakdown" : setupShortEmaDeathContinuation ? "trend_emaDeathContinuation"', source)
        self.assertIn('setupShortEmaDeathContinuation ? "EMA death continuation short: weak structure + EMA death cross + bear fractal/divergence"', source)
        self.assertIn("int scoreShortEmaDeathContinuation = shortEmaDeathContinuationStructureOk and (not dtpBullDominant or bearishReversalContext) ? math.min(100, 34 +", source)
        self.assertIn('activityScore == scoreShortEmaDeathContinuation ? "trend_emaDeathContinuation"', source)
        self.assertIn('candidateSetup == "trend_emaDeathContinuation" ? shortEmaDeathContinuationStructureOk', display)
        self.assertIn('blockedSetup == "trend_emaDeathContinuation" ? shortEmaDeathContinuationStructureOk', display)
        self.assertIn('candidateSetup == "trend_emaDeathContinuation"', display)
        self.assertIn('missingComponents := not shortEmaDeathContinuationStructureOk ? appendSource(missingComponents, "weak_structure")', source)
        self.assertIn('missingComponents := not trendBearEmaCrossSeen ? appendSource(missingComponents, "bear_ema_cross")', source)
        self.assertIn('if not (trendBearFractalSeen or bearDivSeen)', source)
        self.assertIn("jsonBool(\"bear_fractal_seen\", lowerBearFractalSeen or upperBearFractalSeen or trendBearFractalSeen)", source)
        self.assertIn("jsonBool(\"bear_ema_cross_seen\", lowerBearEmaCrossSeen or upperBearEmaCrossSeen or trendBearEmaCrossSeen)", source)
        self.assertIn("emaDeathContinuationShortUsed := setupShortEmaDeathContinuation ? true : emaDeathContinuationShortUsed", source)
        self.assertIn('shortSetup == "trend_emaDeathContinuation" ? "ema_death_continuation"', source)

    def test_mr_regime_filter_anchor_and_mean_target(self):
        source = self.source

        self.assertIn('dtpMrFilterMode = input.string("严格：只放转弱", "DTP MR filter mode", options=["严格：只放转弱", "平衡：只挡初期", "关闭：不挡MR"], group="07 TV Primary Events")', source)
        self.assertIn('mrRangeMaxSdSlopeAtr = input.float(0.10, "MR range max SD slope (x ATR)"', source)
        self.assertIn('dtpMrBlocksPhase(string mode, string phase) =>\n    mode == "关闭：不挡MR" ? false : mode == "严格：只放转弱" ? phase != "weakening" : phase == "early"', source)
        self.assertIn("mrDtpBlocked(string direction, int dtpDirection, string phase, string mode, bool enabled)", source)
        self.assertIn("mrRegimeText(string direction, int dtpDirection, string phase, string mode, bool enabled, float sdSlopeAtrValue)", source)
        self.assertIn('blocked ? "countertrend_blocked" : adverse and phase == "weakening" ? "trend_weakening"', source)
        self.assertNotIn('mrRegimeDisplayName(string regime)', source)
        self.assertIn('mrRegimeDisplayName(string regime)', self.display_source)
        self.assertIn("float sdSlopeAtr = atrRaw > 0.0 ? math.abs(sdSlope) / atrRaw : 999999.0", source)
        self.assertIn('string longMrRegime = mrRegimeText("long", dtpDir, dtpPhase, dtpMrFilterMode, useDtpFilter, sdSlopeAtr)', source)
        self.assertIn('string shortMrRegime = mrRegimeText("short", dtpDir, dtpPhase, dtpMrFilterMode, useDtpFilter, sdSlopeAtr)', source)
        self.assertIn('bool longMrDtpBlocked = mrDtpBlocked("long", dtpDir, dtpPhase, dtpMrFilterMode, useDtpFilter)', source)
        self.assertIn('bool shortMrDtpBlocked = mrDtpBlocked("short", dtpDir, dtpPhase, dtpMrFilterMode, useDtpFilter)', source)
        self.assertIn('bool longMrWeakeningReversalOk = longMrRegime != "trend_weakening" or (lowerBullEmaCrossFresh and (lowerBullFractalFresh or bullDivFresh))', source)
        self.assertIn('bool shortMrWeakeningReversalOk = shortMrRegime != "trend_weakening" or (upperBearEmaCrossFresh and (upperBearFractalFresh or bearDivFresh))', source)
        self.assertIn("bool longMrStructuralAnchorQualified = not structuralAnchorMode or anchorNear(longEntryCandidate, lastPivotLow, atrRaw)", source)
        self.assertIn("bool shortMrStructuralAnchorQualified = not structuralAnchorMode or anchorNear(shortEntryCandidate, lastPivotHigh, atrRaw)", source)
        self.assertIn("float longMrMeanTargetRaw = nearestResistanceAbove(longEntryCandidate, validResistanceLevel(longEntryCandidate, sdReg), validResistanceLevel(longEntryCandidate, emaFast), validResistanceLevel(longEntryCandidate, emaSlow)", source)
        self.assertIn("float shortMrMeanTargetRaw = nearestSupportBelow(shortEntryCandidate, validSupportLevel(shortEntryCandidate, sdReg), validSupportLevel(shortEntryCandidate, emaFast), validSupportLevel(shortEntryCandidate, emaSlow)", source)
        self.assertIn("float longStructureTargetRaw = setupIsMr(longSetup) and longMrMeanTargetAvailable ? longMrMeanTargetRaw : longTrendStructureTargetRaw", source)
        self.assertIn("float shortStructureTargetRaw = setupIsMr(shortSetup) and shortMrMeanTargetAvailable ? shortMrMeanTargetRaw : shortTrendStructureTargetRaw", source)
        self.assertIn('else if longSetup == "mr_sdLower" and longMrDtpBlocked', source)
        self.assertIn('blockLongReason := "mr_dtp_phase_blocked"', source)
        self.assertIn('blockLongReason := "mr_reversal_confirm_missing"', source)
        self.assertIn('blockLongReason := "mr_anchor_unqualified"', source)
        self.assertIn('blockLongReason := "mr_target_space_too_small"', source)
        self.assertIn('else if shortSetup == "mr_sdUpper" and shortMrDtpBlocked', source)
        self.assertIn('blockShortReason := "mr_dtp_phase_blocked"', source)
        self.assertIn('blockShortReason := "mr_reversal_confirm_missing"', source)
        self.assertIn('blockShortReason := "mr_anchor_unqualified"', source)
        self.assertIn('blockShortReason := "mr_target_space_too_small"', source)
        self.assertNotIn("else if useDtpFilter and setupLongMrLower and dtpDir == -1", source)
        self.assertNotIn("else if useDtpFilter and setupShortMrUpper and dtpDir == 1", source)

    def test_post_sd_reversal_trend_setups_do_not_require_active_mr_window(self):
        source = self.source
        display = self.display_source

        self.assertIn('postSdReversalBars = input.int(30, "Post-SD reversal bars"', source)
        self.assertIn('postSdReversalMaxMinutes = input.int(60, "Post-SD reversal max minutes"', source)
        self.assertIn("var int upperSdExtremeBar = na", source)
        self.assertIn("var int lowerSdExtremeBar = na", source)
        self.assertIn("var bool upperPostReversalUsed = false", source)
        self.assertIn("var bool lowerPostReversalUsed = false", source)
        self.assertIn("if canOpenEntry and sdUpperHit\n    upperSdExtremeBar := bar_index", source)
        self.assertIn("if canOpenEntry and sdLowerHit\n    lowerSdExtremeBar := bar_index", source)
        self.assertIn("bool upperSdExtremeFresh = not na(upperSdExtremeBar)", source)
        self.assertIn("bool lowerSdExtremeFresh = not na(lowerSdExtremeBar)", source)

        self.assertIn('setup == "trend_sdUpperBreakdown" ? "SD上轨反转顺势空"', display)
        self.assertIn('setup == "trend_sdLowerBreakout" ? "SD下轨反转顺势多"', display)
        self.assertIn('setup == "trend_sdUpperBreakdown" or setup == "trend_sdLowerBreakout"', source)
        self.assertIn('setup == "trend_sdUpper" or setup == "trend_sdLower" or setup == "trend_sdUpperBreakdown" or setup == "trend_sdLowerBreakout"', source)
        self.assertIn("int longPostLowerBreakoutDirectionComponents = directionComponentCount(lowerBullFractalFresh, bullDivFresh, lowerBullEmaCrossFresh)", source)
        self.assertIn("int shortPostUpperBreakdownDirectionComponents = directionComponentCount(upperBearFractalFresh, bearDivFresh, upperBearEmaCrossFresh)", source)
        self.assertIn("bool setupLongPostLowerBreakout = lowerSdExtremeFresh and not lowerPostReversalUsed and emaFast > emaSlow and close > emaSlow and lowerBullEmaCrossFresh", source)
        self.assertIn("bool setupShortPostUpperBreakdown = upperSdExtremeFresh and not upperPostReversalUsed and emaFast < emaSlow and close < emaSlow and upperBearEmaCrossFresh", source)
        self.assertNotIn("bool setupShortPostUpperBreakdown = upperMrWindowValid", source)
        self.assertNotIn("bool setupLongPostLowerBreakout = lowerMrWindowValid", source)
        self.assertIn('string longSetup = setupLongPostLowerBreakout ? "trend_sdLowerBreakout"', source)
        self.assertIn('string shortSetup = setupShortPostUpperBreakdown ? "trend_sdUpperBreakdown"', source)
        self.assertIn("bool longSignalCandidate = setupLongPostLowerBreakout or setupLongTrendUpper or setupLongMrLower", source)
        self.assertIn("bool shortSignalCandidate = setupShortPostUpperBreakdown or setupShortEmaDeathContinuation or setupShortMrUpper or setupShortTrendLower", source)

        self.assertIn("bool longPostReversalStructuralAnchorQualified = not structuralAnchorMode or anchorNear(longEntryCandidate, lastPivotLow, atrRaw)", source)
        self.assertIn("bool shortPostReversalStructuralAnchorQualified = not structuralAnchorMode or anchorNear(shortEntryCandidate, lastPivotHigh, atrRaw)", source)
        self.assertIn('blockLongReason := "post_reversal_anchor_unqualified"', source)
        self.assertIn('blockShortReason := "post_reversal_anchor_unqualified"', source)
        self.assertIn("float longStructureStopCandidate = longStructureStopAvailable ? longStopSupportBase - atrRaw * structuralSlBufferAtr : longAtrStopCandidate", source)
        self.assertIn("float shortStructureStopCandidate = shortStructureStopAvailable ? shortStopResistanceBase + atrRaw * structuralSlBufferAtr : shortAtrStopCandidate", source)

        self.assertIn("int scoreLongPostLowerBreakout = math.min(100, (lowerSdExtremeFresh ? 34 : 0)", source)
        self.assertIn("int scoreShortPostUpperBreakdown = dtpBullDominant and not bearishReversalContext ? 0 : math.min(100, (upperSdExtremeFresh ? 34 : 0)", source)
        self.assertIn('missingComponents := not lowerSdExtremeFresh ? appendSource(missingComponents, "lower_sd_memory")', source)
        self.assertIn('missingComponents := not upperSdExtremeFresh ? appendSource(missingComponents, "upper_sd_memory")', source)
        self.assertIn('missingText := str.replace_all(missingText, "upper_sd_memory", "上轨记忆")', display)
        self.assertIn('missingText := str.replace_all(missingText, "lower_sd_memory", "下轨记忆")', display)
        self.assertIn('bool candidateUpperWindowReady = candidateSetup == "trend_sdUpper" ? longTrendContextReady : candidateSetup == "trend_sdUpperBreakdown" ? upperSdExtremeFresh', display)
        self.assertIn('bool candidateLowerWindowReady = candidateSetup == "trend_sdLower" ? shortTrendContextReady : candidateSetup == "trend_sdLowerBreakout" ? lowerSdExtremeFresh', display)
        self.assertIn('bool blockedUpperWindowReady = blockedSetup == "trend_sdUpper" ? longTrendContextReady : blockedSetup == "trend_sdUpperBreakdown" ? upperSdExtremeFresh', display)
        self.assertIn('bool blockedLowerWindowReady = blockedSetup == "trend_sdLower" ? shortTrendContextReady : blockedSetup == "trend_sdLowerBreakout" ? lowerSdExtremeFresh', display)

        self.assertIn('jsonBool("lower_sd_extreme_fresh", lowerSdExtremeFresh)', source)
        self.assertIn('jsonBool("upper_sd_extreme_fresh", upperSdExtremeFresh)', source)
        self.assertNotIn('activeSetup == "trend_sdLowerBreakout" and not lowerSdExtremeFresh', source)
        self.assertNotIn('activeSetup == "trend_sdUpperBreakdown" and not upperSdExtremeFresh', source)
        self.assertIn('longSetup == "trend_sdLowerBreakout" ? "post_sd_lower_breakout"', source)
        self.assertIn('shortSetup == "trend_sdUpperBreakdown" ? "post_sd_upper_breakdown"', source)
        self.assertIn("lowerPostReversalUsed := setupLongPostLowerBreakout ? true : lowerPostReversalUsed", source)
        self.assertIn("upperPostReversalUsed := setupShortPostUpperBreakdown ? true : upperPostReversalUsed", source)

    def test_structural_anchor_entry_limit_payload_and_pending_ttl(self):
        source = self.source
        display = self.display_source

        self.assertIn('entryAnchorMode = input.string("setup_structural", "Entry anchor mode", options=["setup_structural", "marketable_cap"], group="05 Risk")', source)
        self.assertIn('entryOrderTtlBars = input.int(1, "Entry order review bars"', source)
        self.assertIn('pendingTrendInvalidationBufferAtr = input.float(0.20, "Pending trend invalidation buffer (x ATR)"', source)
        self.assertIn('pendingTrendRecheckBars = input.int(2, "Pending trend soft invalid recheck bars"', source)
        self.assertIn("entryAnchorZoneAtr = input.float(0.15, \"Entry anchor zone (x ATR)\"", source)
        self.assertIn("float longStructuralAnchorLevel = nearestSupportBelow(longReferenceEntry", source)
        self.assertIn("float shortStructuralAnchorLevel = nearestResistanceAbove(shortReferenceEntry", source)
        self.assertIn("float longStructuralEntryRaw = math.min(longReferenceEntry, longStructuralAnchorLevel + atrRaw * entryAnchorZoneAtr)", source)
        self.assertIn("float shortStructuralEntryRaw = math.max(shortReferenceEntry, shortStructuralAnchorLevel - atrRaw * entryAnchorZoneAtr)", source)
        self.assertIn("bool longEntryAnchorTouched = structuralAnchorMode and not na(longEntryCandidate) and low <= longEntryCandidate", source)
        self.assertIn("bool shortEntryAnchorTouched = structuralAnchorMode and not na(shortEntryCandidate) and high >= shortEntryCandidate", source)
        self.assertIn('longEntryAnchorReason := longEntryAnchorTouched ? appendAnchorReason(longEntryAnchorReason, "锚点已触及") : longEntryAnchorReason', source)
        self.assertIn('shortEntryAnchorReason := shortEntryAnchorTouched ? appendAnchorReason(shortEntryAnchorReason, "锚点已触及") : shortEntryAnchorReason', source)
        self.assertIn("bool longEntryAnchorAllowed = not structuralAnchorMode or ((longEntryAnchorTouched or entryAnchorValid(longReferenceEntry, longEntryCandidate, atrRaw)) and longEntryCandidate <= longReferenceEntry)", source)
        self.assertIn("bool shortEntryAnchorAllowed = not structuralAnchorMode or ((shortEntryAnchorTouched or entryAnchorValid(shortReferenceEntry, shortEntryCandidate, atrRaw)) and shortEntryCandidate >= shortReferenceEntry)", source)
        self.assertIn("jsonNum(\"planned_entry_price\", plannedEntry)", source)
        self.assertIn('jsonStr("entry_price_plan", structuralAnchorMode ? "structural_anchor_limit" : "tv_direct_bounded_limit")', source)
        self.assertIn('jsonStr("entry_anchor_reason", entryAnchorReason == "" ? "none" : entryAnchorReason)', source)
        self.assertIn('jsonStr("risk_model", structuralAnchorMode ? "setup_aware_structural_v1" : "tv_direct_bounded_limit_v1")', source)
        self.assertIn("activePendingEntry := true", source)
        self.assertIn('strategy.cancel("TV-L")', source)
        self.assertIn('strategy.cancel("TV-S")', source)
        self.assertIn('"\\nref " + str.tostring(longReferenceEntry', display)
        self.assertIn('"\\nref " + str.tostring(shortReferenceEntry', display)
        self.assertIn("bool pendingFilledNow = confirmed and activePendingEntry and strategy.position_size != 0", source)
        self.assertIn("bool pendingEntryExpired = confirmed and activePendingEntry and strategy.position_size == 0", source)
        self.assertNotIn("pendingSetupWindowExpired", source)
        self.assertIn("bool longActionable = longSignalCandidate and not blockLong", source)
        self.assertIn("bool shortActionable = shortSignalCandidate and not blockShort", source)
        self.assertIn("bool pendingOppositeLongActionable = confirmed and activePendingEntry and strategy.position_size == 0 and activeDirection == -1 and longActionable", source)
        self.assertIn("bool pendingOppositeShortActionable = confirmed and activePendingEntry and strategy.position_size == 0 and activeDirection == 1 and shortActionable", source)
        self.assertIn("bool pendingActionableConflict = confirmed and activePendingEntry and strategy.position_size == 0 and longActionable and shortActionable", source)
        self.assertIn("bool pendingOppositeOrConflict = pendingActionableConflict or pendingOppositeLongActionable or pendingOppositeShortActionable", source)
        self.assertNotIn("bool pendingOppositeOrConflict = confirmed and activePendingEntry and strategy.position_size == 0 and (conflict or", source)
        self.assertIn("bool pendingSameDirectionContinuation = confirmed and activePendingEntry and strategy.position_size == 0", source)
        self.assertIn("bool pendingLongEmaSoftReversed = emaFast < emaSlow or close < emaSlow", source)
        self.assertIn("bool pendingShortEmaSoftReversed = emaFast > emaSlow or close > emaSlow", source)
        self.assertIn("bool pendingLongEmaBufferBroken = emaFast < emaSlow and close < emaSlow - pendingTrendInvalidationBuffer", source)
        self.assertIn("bool pendingShortEmaBufferBroken = emaFast > emaSlow and close > emaSlow + pendingTrendInvalidationBuffer", source)
        self.assertIn('bool pendingLongTrendSupportFailed = dtpDir == -1 or mtfLongStatus == "block"', source)
        self.assertIn('bool pendingShortTrendSupportFailed = dtpDir == 1 or mtfShortStatus == "block"', source)
        self.assertIn("bool pendingLongHardInvalidated = pendingLongEmaBufferBroken and pendingLongTrendSupportFailed", source)
        self.assertIn("bool pendingShortHardInvalidated = pendingShortEmaBufferBroken and pendingShortTrendSupportFailed", source)
        self.assertIn("bool pendingHardInvalidated = confirmed and activePendingEntry and strategy.position_size == 0", source)
        self.assertIn("bool pendingSoftInvalidated = confirmed and activePendingEntry and strategy.position_size == 0 and not pendingHardInvalidated", source)
        self.assertIn("bool pendingSoftRecheckFailed = pendingEntryExpired and pendingSoftInvalidated and not pendingSameDirectionContinuation", source)
        self.assertIn("bool pendingTrendInvalidated = pendingHardInvalidated", source)
        self.assertNotIn('dtpDir == -1 or mtfLongStatus == "block" or pendingLongEmaHardReversed', source)
        self.assertNotIn('dtpDir == 1 or mtfShortStatus == "block" or pendingShortEmaHardReversed', source)
        self.assertIn("bool pendingTrendStillValid = confirmed and activePendingEntry and strategy.position_size == 0 and not pendingTrendInvalidated", source)
        self.assertIn("bool pendingEntryRenewNow = pendingEntryExpired and pendingTrendStillValid and not pendingSoftRecheckFailed", source)
        self.assertIn("int pendingRenewBars = pendingSoftInvalidated ? pendingTrendRecheckBars : entryOrderTtlBars", source)
        self.assertIn("activeEntryOrderExpiresBar := bar_index + pendingRenewBars", source)
        self.assertIn('pendingTrendInvalidated ? "trend_invalidated"', source)
        self.assertIn('pendingSoftRecheckFailed ? "soft_trend_recheck_failed"', source)
        self.assertIn('pendingEntryExpired and not pendingEntryRenewNow ? "entry_ttl_expired"', source)
        self.assertIn('pendingOppositeOrConflict ? "opposite_signal_or_conflict" : pendingEntryWindowExpired', source)
        self.assertNotIn("not pendingSetupWindowExpired", source)
        self.assertNotIn('pendingSetupWindowExpired ? "setup_window_expired"', source)
        self.assertNotIn('pendingEodCancel ? "pending_eod_cancel" : pendingEntryExpired ? "entry_ttl_expired"', source)
        self.assertNotIn('" / TTL " + str.tostring(entryOrderTtlBars, "#")', source)
        self.assertNotIn("cancelPrimaryText", source)
        self.assertNotIn("cancelSecondaryText", source)
        self.assertIn("bool pendingCancelNow = pendingCancelReason != \"\"", source)
        self.assertIn("bool enterLong = canOpenEntry and flatForEntry and allowLong and longSignalCandidate", source)
        self.assertIn("bool enterShort = canOpenEntry and flatForEntry and allowShort and shortSignalCandidate", source)

    def test_entry_fill_confirmation_stays_in_core(self):
        source = self.source
        display = self.display_source

        self.assertIn('enableFillConfirmAlerts = input.bool(false, "Alert on TV strategy fill confirmation", group="07 TV Primary Events")', source)
        self.assertIn("var int activeEntrySignalBar = na", source)
        self.assertIn("buildEntryFillPayload(string eventIdValue, string positionIdValue, float actualFillPrice)", source)
        self.assertIn('basePayload("entry_fill", eventIdValue, positionIdValue)', source)
        self.assertIn('jsonNum("actual_fill_price", actualFillPrice)', source)
        self.assertIn('jsonNum("planned_entry_price", activeEntry)', source)
        self.assertIn('jsonNum("submitted_entry_limit_price", activeSubmittedEntryLimit)', source)
        self.assertIn('jsonIntNullable("entry_signal_bar_index", activeEntrySignalBar)', source)
        self.assertIn('jsonInt("fill_bar_index", bar_index)', source)
        self.assertIn('jsonInt("entry_order_age_bars", entryOrderAgeBars)', source)
        self.assertIn('jsonNum("strategy_position_size", strategy.position_size)', source)
        self.assertIn('jsonStr("order_lifecycle_model", "core_strategy_shadow_v1")', source)
        self.assertIn('jsonStr("fill_confirmation_source", "tv_strategy_position_size")', source)
        self.assertIn('jsonStr("limit_fill_note", "TradingView broker emulator controls actual fill")', source)
        self.assertIn("float actualFillPrice = strategy.position_avg_price > 0.0 ? strategy.position_avg_price : activeEntry", source)
        self.assertIn("if enableAlerts and enableFillConfirmAlerts", source)
        self.assertIn('alert(buildEntryFillPayload(eventId("entry_fill", activeSetup), activePositionId, actualFillPrice), alert.freq_all)', source)
        self.assertIn("activeEntrySignalBar := bar_index", source)
        self.assertIn("activeEntryBar := na", source)

        pending_fill_index = source.index("bool pendingFilledNow = confirmed and activePendingEntry and strategy.position_size != 0")
        pending_cancel_index = source.index("bool pendingCancelNow = pendingCancelReason != \"\"")
        self.assertLess(pending_fill_index, pending_cancel_index)
        self.assertNotIn("buildEntryFillPayload", display)
        self.assertNotIn("enableFillConfirmAlerts", display)

    def test_display_pending_entry_lifecycle_is_visual_only(self):
        display = self.display_source

        self.assertIn('showPendingEntryLifecycle = input.bool(true, "Show pending entry lifecycle", group="08 Display")', display)
        self.assertIn("var bool displayShadowPendingEntry = false", display)
        self.assertIn("var int displayShadowSignalBar = na", display)
        self.assertIn("var int displayShadowExpiresBar = na", display)
        self.assertIn("var string displayShadowCancelReason = \"\"", display)
        self.assertIn("bool displayFlatForEntry = not displayShadowPendingEntry and not displayPendingEntryTouchedNow", display)
        self.assertIn("bool displayEnterLong = canOpenEntry and displayFlatForEntry and allowLong and longSignalCandidate", display)
        self.assertIn("bool displayEnterShort = canOpenEntry and displayFlatForEntry and allowShort and shortSignalCandidate", display)
        self.assertIn("if showPendingEntryLifecycle and displayEnterLong", display)
        self.assertIn("if showPendingEntryLifecycle and displayEnterShort", display)
        self.assertIn("displayShadowExpiresBar := bar_index + entryOrderTtlBars", display)
        self.assertIn("bool displayPendingLongTouchedNow = confirmed and showPendingEntryLifecycle and displayShadowPendingEntry and displayShadowDirection == 1 and bar_index > displayShadowSignalBar and low <= displayShadowEntry", display)
        self.assertIn("bool displayPendingShortTouchedNow = confirmed and showPendingEntryLifecycle and displayShadowPendingEntry and displayShadowDirection == -1 and bar_index > displayShadowSignalBar and high >= displayShadowEntry", display)
        self.assertIn("bool displayPendingEntryExpiredNow = confirmed and showPendingEntryLifecycle and displayShadowPendingEntry and not na(displayShadowExpiresBar) and bar_index > displayShadowExpiresBar", display)
        self.assertIn("bool displayPendingEntryWindowExpired = confirmed and showPendingEntryLifecycle and displayShadowPendingEntry and not inEntryWindow", display)
        self.assertIn("bool displayPendingAnchorInvalidated = confirmed and showPendingEntryLifecycle and displayShadowPendingEntry and structuralAnchorMode", display)
        self.assertIn("bool displayPendingOppositeOrConflict = displayPendingActionableConflict or displayPendingOppositeLongActionable or displayPendingOppositeShortActionable", display)
        self.assertIn("bool displayPendingEntryRenewNow = displayPendingEntryExpiredNow and displayPendingTrendStillValid and not displayPendingSoftRecheckFailed", display)
        self.assertIn("displayShadowExpiresBar := bar_index + displayPendingRenewBars", display)
        self.assertIn('string displayPendingCancelReason = displayPendingEodCancel ? "pending_eod_cancel" : displayPendingOppositeOrConflict ? "opposite_signal_or_conflict"', display)
        self.assertIn("bool displayPendingCancelNow = showPendingEntryLifecycle and displayPendingCancelReason != \"\"", display)
        self.assertIn("int displayLifecycleDirection = displayShadowDirection", display)
        self.assertIn("float displayLifecycleEntry = displayShadowEntry", display)
        self.assertIn("bool pendingDisplayLifecycleVisible = pendingDisplayWaiting or displayPendingEntryTouchedNow or displayPendingCancelNow", display)
        self.assertIn('string longEntryDetailText = "信号满足\\nCore计划挂多\\n"', display)
        self.assertIn('string shortEntryDetailText = "信号满足\\nCore计划挂空\\n"', display)
        self.assertIn('string longEntryCompactText = "待触及 多·" + decisionSetupTag(longSetup)', display)
        self.assertIn('string shortEntryCompactText = "待触及 空·" + decisionSetupTag(shortSetup)', display)
        self.assertIn('string pendingTouchDetailText = "Core模拟触及\\n"', display)
        self.assertIn('string pendingCancelDetailText = "Core模拟撤销: " + displayPendingCancelReason', display)
        self.assertIn("Display shadow，不代表 TV strategy 已成交；真实成交看 Core Strategy Tester / Core entry_fill / 券商订单", display)
        self.assertIn('indicator(title="Signal Strategy Display[Glory]", overlay=true, max_labels_count=500, max_lines_count=20)', display)
        self.assertIn('showCurrentPlanLines = input.bool(true, "Show current Core plan lines", group="08 Display")', display)
        self.assertIn("float displayEntryPlan = not na(displaySignalEntryPlan) ? displaySignalEntryPlan : pendingDisplayWaiting ? displayLifecycleEntry : na", display)
        self.assertIn("bool displayPlanLinesActive = showCurrentPlanLines and not na(displayEntryPlan) and not displayPendingEntryTouchedNow and not displayPendingCancelNow", display)
        self.assertIn("var line displayEntryLine = na", display)
        self.assertIn("int planLineEndBar = bar_index + 1", display)
        self.assertIn("displayEntryLine := line.new(planLineStartBar, displayEntryPlan, planLineEndBar, displayEntryPlan", display)
        self.assertIn("line.set_xy1(displayEntryLine, planLineStartBar, displayEntryPlan)", display)
        self.assertIn("line.set_xy2(displayEntryLine, planLineEndBar, displayEntryPlan)", display)
        self.assertIn("line.delete(displayEntryLine)", display)
        self.assertIn("line.delete(displayRunnerLine)", display)
        self.assertNotIn('plot(displayEntryPlan, "Display Plan Entry"', display)
        self.assertNotIn('plot(displayStopPlan, "Display SL"', display)
        self.assertNotIn('plot(displayTargetPlan, "Display TP"', display)
        self.assertNotIn('plot(displayRunnerActivation, "Display Runner Activation"', display)
        self.assertIn('string pendingDisplayStatus = displayPendingEntryTouchedNow ? "Core模拟触及" : displayPendingCancelNow ? "Core模拟撤销" : pendingDisplayWaiting ? "Core挂单中" : ""', display)
        self.assertIn('string statusText = displayEnterLong or displayEnterShort ? "Core挂单中"', display)
        self.assertIn('string statusComponents = pendingDisplayStatus != "" ? displayPendingCancelNow ? "Core模拟撤销: " + cancelReasonDisplayName(displayPendingCancelReason) : "成交确认看 Core"', display)
        self.assertIn("Core挂单中", display)
        self.assertIn("Core模拟触及", display)
        self.assertIn("Core模拟撤销", display)
        self.assertNotIn("已触及计划价", display)
        self.assertNotIn("未触及·过期", display)
        self.assertNotIn("应成交", display)
        self.assertNotIn("买入", display)

    def test_mr_window_freshness_and_mr_exit_guards(self):
        source = self.source

        self.assertIn('mrWindowBars = input.int(30, "MR window bars"', source)
        self.assertIn('mrWindowMaxMinutes = input.int(60, "MR window max minutes"', source)
        self.assertIn('mrComponentFreshBars = input.int(30, "MR component freshness bars"', source)
        self.assertIn('mrExpireOnMeanTouch = input.bool(true, "Expire MR window after mean touch"', source)
        self.assertIn("bool lowerWindowTimeExpired = lowerWindowActive and not na(lowerWindowStartTime)", source)
        self.assertIn("bool lowerWindowMeanTouched = lowerWindowActive and mrExpireOnMeanTouch", source)
        self.assertIn("var bool lowerWindowMeanExpired = false", source)
        self.assertIn("var bool upperWindowMeanExpired = false", source)
        self.assertIn("bool lowerWindowHardExpired = lowerWindowBarExpired or lowerWindowTimeExpired", source)
        self.assertIn("bool upperWindowHardExpired = upperWindowBarExpired or upperWindowTimeExpired", source)
        self.assertIn("bool lowerWindowExpired = lowerWindowHardExpired or lowerWindowMeanExpired or lowerWindowMeanTouched", source)
        self.assertIn("bool upperWindowExpired = upperWindowHardExpired or upperWindowMeanExpired or upperWindowMeanTouched", source)
        self.assertIn("if lowerWindowHardExpired and not lowerActivationEvent\n    lowerWindowActive := false", source)
        self.assertIn("if upperWindowHardExpired and not upperActivationEvent\n    upperWindowActive := false", source)
        self.assertIn("bool lowerMrWindowValid = lowerWindowValid and not lowerWindowMeanExpired and not lowerWindowMeanTouched", source)
        self.assertIn("bool upperMrWindowValid = upperWindowValid and not upperWindowMeanExpired and not upperWindowMeanTouched", source)
        self.assertIn("if lowerWindowMeanTouched and not lowerActivationEvent\n    lowerWindowMeanExpired := true", source)
        self.assertIn("if upperWindowMeanTouched and not upperActivationEvent\n    upperWindowMeanExpired := true", source)
        self.assertIn("componentFresh(int componentBar)", source)
        self.assertIn('blockShortReason := "mr_dtp_phase_blocked"', source)
        self.assertIn('blockShortReason := "mr_anchor_unqualified"', source)
        self.assertIn('blockShortReason := "mr_target_space_too_small"', source)
        self.assertIn('blockShortReason := "mr_ema_cross_missing"', source)
        self.assertIn('blockShortReason := "mr_component_stale"', source)
        self.assertNotIn('activeSetup == "trend_sdLower" and lowerWindowHardExpired', source)
        self.assertNotIn('activeSetup == "trend_sdUpper" and upperWindowHardExpired', source)
        self.assertIn('pendingExitReason := "mr_structure_invalidated"', source)
        self.assertIn('pendingExitReason := "mr_time_stop"', source)
        self.assertIn('riskUpdateReason := "mr_checkpoint_lock"', source)

    def test_trend_no_follow_through_risk_controls_are_serialized(self):
        source = self.source

        self.assertIn('noFollowThroughBars = input.int(8, "No-follow-through bars"', source)
        self.assertIn('noFollowThroughMinMfeR = input.float(0.30, "No-follow-through min MFE (R)"', source)
        self.assertIn('noFollowThroughCompressedStopR = input.float(0.50, "No-follow-through compressed stop (R)"', source)
        self.assertIn('earlyAdverseBars = input.int(5, "Early adverse exit bars"', source)
        self.assertIn('earlyAdverseExitR = input.float(0.50, "Early adverse exit (R)"', source)
        self.assertIn('noFollowThroughDisableAfterMfeR = input.float(0.60, "Disable no-follow after MFE (R)"', source)
        self.assertIn('pendingExitReason := earlyAdverseStopNow ? "adverse_early_stop" : "opposite_structure_exit"', source)
        self.assertIn("var float activeMaeR = 0.0", source)
        self.assertIn('jsonBool("trend_continuation_context", setup == "trend_sdUpper" ? bullTrendContinuationContext : setup == "trend_sdLower" ? bearTrendContinuationContext : false)', source)
        self.assertIn('jsonStr("direction_decision", setup == "trend_sdUpper" and bullTrendContinuationContext ? "dtp_bull_sd_upper_trend_long" : setup == "trend_sdLower" and bearTrendContinuationContext ? "dtp_bear_sd_lower_trend_short" : "none")', source)
        self.assertIn('jsonStr("primary_reason", reason)', source)
        self.assertIn('jsonStr("secondary_reason", "none")', source)
        self.assertIn('jsonInt("bars_in_trade", barsInTradePayload)', source)
        self.assertIn('jsonNum("mfe_r", activeMfeR)', source)
        self.assertIn('jsonNum("mae_r", activeMaeR)', source)
        self.assertIn("activeMaeR := math.max(nz(activeMaeR, 0.0), maeRNow)", source)
        self.assertIn("bool noFollowEligible = setupIsTrend(activeSetup) and not activeRunnerActive and activeMfeR < noFollowThroughDisableAfterMfeR and initialRisk > 0.0", source)
        self.assertIn("bool earlyAdverseStopNow = noFollowEligible and barsInTrade <= earlyAdverseBars and activeMaeR >= earlyAdverseExitR and activeOppositeStructureBroken", source)
        self.assertIn("bool oppositeStructureExitNow = noFollowEligible and barsInTrade > earlyAdverseBars and activeMaeR >= earlyAdverseExitR and activeOppositeStructureBroken", source)
        self.assertIn("bool noFollowCompressNow = noFollowEligible and barsInTrade >= noFollowThroughBars and activeMfeR < noFollowThroughMinMfeR", source)
        self.assertIn('pendingExitReason := earlyAdverseStopNow ? "adverse_early_stop" : "opposite_structure_exit"', source)
        self.assertIn("float compressedStop = activeDirection == 1 ? activeEntry - initialRisk * noFollowThroughCompressedStopR : activeEntry + initialRisk * noFollowThroughCompressedStopR", source)
        self.assertIn('riskUpdateReason := "no_follow_through_stop_compress"', source)

    def test_risk_update_sequence_is_incremented_and_serialized(self):
        source = self.source

        self.assertIn("var int activeRiskUpdateSeq = 0", source)
        self.assertIn('jsonInt("risk_update_seq", activeRiskUpdateSeq)', source)
        self.assertNotIn('alert(buildRiskPayload(eventId("risk_update", "initial")', source)
        self.assertNotIn('"initial_protection"', source)
        self.assertIn("activeRiskUpdateSeq := activeRiskUpdateSeq + 1\n        alert(buildRiskPayload(eventId(\"risk_update\", reasonForEvent)", source)

    def test_cancel_alert_payload_and_signal_fill_visuals_are_separate(self):
        source = self.source
        display = self.display_source

        self.assertIn("buildCancelPayload(string eventIdValue, string positionIdValue, string cancelReason)", source)
        self.assertIn('basePayload("cancel", eventIdValue, positionIdValue)', source)
        self.assertIn('jsonStr("origin_signal_id", activeSignalId)', source)
        self.assertIn('jsonStr("cancel_scope", "trade_intent")', source)
        self.assertIn('jsonStr("cancel_policy", "cancel_unfilled_or_close_filled")', source)
        self.assertIn('jsonNum("submitted_entry_limit_price", activeSubmittedEntryLimit)', source)
        self.assertIn('jsonBool("plan_price_locked", true)', source)
        self.assertIn('jsonStr("pending_plan_policy", "lock_original_plan")', source)
        self.assertIn('jsonNum("pending_trend_invalidation_buffer_atr", pendingTrendInvalidationBufferAtr)', source)
        self.assertIn('jsonBool("tv_position_filled", strategy.position_size != 0)', source)
        self.assertIn("alert(buildCancelPayload(eventId(\"cancel\", pendingCancelReason), activePositionId, pendingCancelReason), alert.freq_all)", source)
        self.assertIn("var bool activeCancelSent = false", source)
        self.assertIn("activeCancelSent := true", source)
        self.assertNotIn("信号已发出", source)
        self.assertNotIn("TV模拟成交", source)
        self.assertNotIn("信号撤销", source)
        self.assertIn('"信号满足\\nCore计划挂多\\n"', display)
        self.assertIn('"信号满足\\nCore计划挂空\\n"', display)
        self.assertIn("flowLabelText(longEntryCompactText, longEntryDetailText)", display)
        self.assertIn("flowLabelText(shortEntryCompactText, shortEntryDetailText)", display)


if __name__ == "__main__":
    unittest.main()
