import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
CORE_PINE_PATH = REPO_ROOT / "tradingview" / "new" / "Signal_Strategy_Core[Glory].pine"
DISPLAY_PINE_PATH = REPO_ROOT / "tradingview" / "new" / "Signal_Strategy_Display[Glory].pine"
COMMON_PINE_PATH = REPO_ROOT / "tradingview" / "new" / "Signal_Strategy_Common[Glory].pine"
LIBS_DIR = REPO_ROOT / "tradingview" / "new" / "libs"
FORMAT_PINE_PATH = LIBS_DIR / "SSC_Lib_Format[Glory].pine"
RISK_PINE_PATH = LIBS_DIR / "SSC_Lib_Risk[Glory].pine"
LEVELS_PINE_PATH = LIBS_DIR / "SSC_Lib_Levels[Glory].pine"
MODEL_PINE_PATH = LIBS_DIR / "SSC_Lib_Model[Glory].pine"
V1_CORE_PINE_PATH = REPO_ROOT / "tradingview" / "v1" / "Signal_Strategy_Core[Glory].pine"
V1_DISPLAY_PINE_PATH = REPO_ROOT / "tradingview" / "v1" / "Signal_Strategy_Display[Glory].pine"


class TradingViewStrategyCorePineTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.source = CORE_PINE_PATH.read_text(encoding="utf-8")
        cls.display_source = DISPLAY_PINE_PATH.read_text(encoding="utf-8")
        cls.format_source = FORMAT_PINE_PATH.read_text(encoding="utf-8")
        cls.risk_source = RISK_PINE_PATH.read_text(encoding="utf-8")
        cls.levels_source = LEVELS_PINE_PATH.read_text(encoding="utf-8")
        cls.model_source = MODEL_PINE_PATH.read_text(encoding="utf-8")

    def test_core_and_display_scripts_have_separate_responsibilities(self):
        core = self.source
        display = self.display_source

        self.assertIn('strategy(title="Signal Strategy Core[Glory]"', core)
        self.assertIn('indicator(title="Signal Strategy Display[Glory]"', display)
        self.assertIn("alert(", core)
        self.assertIn("strategy.entry", core)
        self.assertIn("strategy.exit", core)
        self.assertNotIn("label.new(", core)
        self.assertNotIn("plot(", core)
        self.assertNotIn("plotshape(", core)
        self.assertNotIn("table.", core)
        self.assertNotIn("line.", core)
        self.assertIn("label.new(", display)
        self.assertIn("plotshape(", display)
        self.assertNotIn("table.", display)
        self.assertNotIn("var table", display)
        self.assertNotIn("strategy.", display)
        self.assertNotIn("strategy(", display)
        self.assertNotIn("alert(", display)
        self.assertNotIn("basePayload", display)
        self.assertNotIn("jsonStr(", display)
        self.assertNotIn("jsonNum(", display)
        self.assertNotIn("jsonBool(", display)

    def test_v1_archive_is_preserved(self):
        self.assertTrue(V1_CORE_PINE_PATH.exists())
        self.assertTrue(V1_DISPLAY_PINE_PATH.exists())
        self.assertIn('string STRATEGY_VERSION = "SSC_v1_20260613_alert_slim"', V1_CORE_PINE_PATH.read_text(encoding="utf-8"))
        self.assertIn('indicator(title="Signal Strategy Display[Glory]"', V1_DISPLAY_PINE_PATH.read_text(encoding="utf-8"))

    def test_v4_model_identity_and_scope_are_explicit(self):
        source = self.source
        display = self.display_source

        self.assertIn('string STRATEGY_VERSION = "SSC_v4_20260618_quick_ema_scalp"', source)
        self.assertIn('string ENTRY_WINDOW_MODEL = "quick_ema_scalp_v1"', source)
        self.assertIn('string TP_SL_MODEL = "quick_ema20_scalp_tp_v1"', source)
        self.assertIn('string RISK_MODEL = "small_stop_75dollar_scalp_v1"', source)
        self.assertIn('string TRADE_MODEL = "quick_ema_scalp_v1"', source)
        self.assertIn('string STRATEGY_VERSION = "SSD_v4_20260618_quick_ema_scalp"', display)
        self.assertIn('string ENTRY_WINDOW_MODEL = "quick_ema_scalp_v1"', display)
        self.assertIn('Display shadow，不代表 TV strategy 已成交', display)

    def test_universal_small_stop_gate_is_hard_filter(self):
        source = self.source
        display = self.display_source

        for text in (source, display):
            self.assertIn('predictiveMaxRiskDollars = input.float(37.5, "Predictive max trial risk ($)"', text)
            self.assertIn('confirmedMaxRiskDollars = input.float(75.0, "Confirmed max trial risk ($)"', text)
            self.assertIn('riskQtySafetyPct = input.float(0.95, "Risk qty safety pct"', text)
            self.assertIn('riskQtyBufferAtr = input.float(0.03, "Risk qty safety buffer (x ATR)"', text)
            self.assertIn('useNotionalCap = input.bool(false, "Apply notional cap after risk qty"', text)
            self.assertIn('predictiveMaxStopAtr = input.float(0.70, "Predictive max stop distance (x ATR)"', text)
            self.assertIn('confirmedMaxStopAtr = input.float(0.90, "Confirmed max stop distance (x ATR)"', text)
            self.assertIn('predictiveMaxStopBps = input.float(60.0, "Predictive max stop distance (bps)"', text)
            self.assertIn('confirmedMaxStopBps = input.float(80.0, "Confirmed max stop distance (bps)"', text)
            self.assertIn('stopBoundedEntry(int direction, float proposedEntry, float stopPrice, float atrValue, float maxAtrMultiple, float maxBps) =>', text)
            self.assertIn('calcTrialQty(float entryPrice, float stopPrice, float maxRiskDollars) =>', text)
            self.assertIn('risklib.smallStopTrialAllowed(', text)
            self.assertIn('risklib.smallStopGateReason(', text)
            self.assertIn('risklib.stopBoundedEntry(direction, proposedEntry, stopPrice, atrValue, maxAtrMultiple, maxBps, syminfo.mintick)', text)
            self.assertIn('risklib.calcTrialQty(entryPrice, stopPrice, maxRiskDollars, atr, riskQtyBufferAtr, riskQtySafetyPct, useNotionalCap, positionAmount, syminfo.mintick)', text)
            self.assertIn('scalpMinExpectedR = input.float(1.50, "Scalp minimum expected reward (R)"', text)
            self.assertIn('minTpRunnerGapR = input.float(0.50, "Minimum TP-runner gap (R)"', text)
            self.assertIn('allowSameBarRunnerAfterFill = input.bool(false, "Allow same-bar runner after fill"', text)
            self.assertIn('minEmaProfitAtr = input.float(0.80, "Minimum EMA target room (x ATR)"', text)
            self.assertIn('rsiLen = input.int(14, "Scalp RSI length"', text)
            self.assertNotIn('minStopRiskFloorDollars', text)
            self.assertNotIn('Minimum stop breathing room', text)

    def test_split_libraries_contain_shared_display_helpers(self):
        core = self.source
        display = self.display_source
        format_lib = self.format_source
        risk_lib = self.risk_source
        levels_lib = self.levels_source
        model_lib = self.model_source

        self.assertFalse(COMMON_PINE_PATH.exists())
        for path in (FORMAT_PINE_PATH, RISK_PINE_PATH, LEVELS_PINE_PATH, MODEL_PINE_PATH):
            self.assertTrue(path.exists())
        self.assertIn('library("SSC_Lib_Format_Glory", overlay=true)', format_lib)
        self.assertIn('library("SSC_Lib_Risk_Glory", overlay=true)', risk_lib)
        self.assertIn('library("SSC_Lib_Levels_Glory", overlay=true)', levels_lib)
        self.assertIn('library("SSC_Lib_Model_Glory", overlay=true)', model_lib)
        for text in (core, display):
            self.assertIn('import o8431/SSC_Lib_Format_Glory/2 as fmtlib', text)
            self.assertIn('import o8431/SSC_Lib_Risk_Glory/1 as risklib', text)
            self.assertIn('import o8431/SSC_Lib_Levels_Glory/1 as levellib', text)
            self.assertIn('import o8431/SSC_Lib_Model_Glory/1 as modellib', text)
            self.assertNotIn('Signal_Strategy_Common_Glory', text)
            self.assertNotIn('Signal_Strategy_Text_Glory', text)
            self.assertNotIn('as text', text)
            self.assertNotIn('text.', text)
            self.assertNotIn('common.', text)
        for export in (
            "export fmt(",
            "export moneyText(",
            "export qtyText(",
            "export setupDisplayName(",
            "export reasonCn(",
            "export exitReasonShortName(",
        ):
            self.assertIn(export, format_lib)
        for export in (
            "export riskPerShare(",
            "export riskDollars(",
            "export stopBoundedEntry(",
            "export smallStopTrialAllowed(",
            "export smallStopGateReason(",
            "export calcTrialQty(",
            "export scalpEmaTarget(",
            "export floatingStructureStop(",
        ):
            self.assertIn(export, risk_lib)
        for export in (
            "export nearestBelow(",
            "export nearestAbove(",
            "export appendNearSource(",
        ):
            self.assertIn(export, levels_lib)
        for export in (
            "export marketRegime(",
            "export topCountertrendBlockReason(",
            "export bottomCountertrendBlockReason(",
            "export conflictNoClearEdge(",
            "export selectedLong(",
            "export selectedShort(",
            "export selectedSetup(",
            "export tradeFamily(",
        ):
            self.assertIn(export, model_lib)
        for reason in (
            "tp_runner_gap_too_small",
            "dominant_bear_countertrend_block",
            "dominant_bull_countertrend_block",
            "countertrend_reclaim_missing",
            "fresh_low_continuation_risk",
            "fresh_high_continuation_risk",
            "attack_volume_cooling_block",
            "shock_day_countertrend_block",
            "model_conflict_no_clear_edge",
        ):
            self.assertIn(f'"{reason}"', format_lib + model_lib)

    def test_countertrend_reclaim_uses_stable_barssince_series(self):
        for text in (self.source, self.display_source):
            self.assertIn("int topCountertrendBreakdownBars = nz(ta.barssince(not topCountertrendBreakdownClose), countertrendReclaimCloseBars)", text)
            self.assertIn("int bottomCountertrendReclaimBars = nz(ta.barssince(not bottomCountertrendReclaimClose), countertrendReclaimCloseBars)", text)
            self.assertIn("topCountertrendBreakdownClose and topCountertrendBreakdownBars >= countertrendReclaimCloseBars - 1", text)
            self.assertIn("bottomCountertrendReclaimClose and bottomCountertrendReclaimBars >= countertrendReclaimCloseBars - 1", text)
            self.assertNotIn("topCountertrendBreakdownClose and nz(ta.barssince", text)
            self.assertNotIn("bottomCountertrendReclaimClose and nz(ta.barssince", text)

    def test_only_current_setup_families_are_used_in_current_files(self):
        for text in (self.source, self.display_source):
            self.assertIn('"trend_support_long"', text)
            self.assertIn('"trend_resistance_short"', text)
            self.assertIn('"probe_2b_top_short"', text)
            self.assertIn('"probe_2b_bottom_long"', text)
            self.assertNotIn('"mr_sdLower"', text)
            self.assertNotIn('"mr_sdUpper"', text)
            self.assertNotIn('"trend_sdUpper"', text)
            self.assertNotIn('"trend_sdLower"', text)
            self.assertNotIn('"trend_emaDeathContinuation"', text)

    def test_trend_entries_require_pullback_to_strong_structure(self):
        source = self.source

        self.assertIn('referenceSession = input.session("0930-1600", "Reference day structure session"', source)
        self.assertIn('bool referenceDayReset = timeframe.change("D") or referenceSessionStarted', source)
        self.assertIn('trendHasHH', source)
        self.assertIn('trendHasHL', source)
        self.assertIn('trendHasLL', source)
        self.assertIn('trendHasLH', source)
        self.assertIn('bool strongStructTrendLong = dtpBull and emaFast > emaMid and emaMid > emaSlow and close >= sdMid and trendHasHH and trendHasHL', source)
        self.assertIn('bool strongStructTrendShort = dtpBear and emaFast < emaMid and emaMid < emaSlow and close <= sdMid and trendHasLL and trendHasLH', source)
        self.assertIn('bool dayRangeClear = dayRangeFormed and dayRangeAtr >= minClearDayRangeAtr', source)
        self.assertIn('bool dominantTrendLong = dayRangeClear and dtpBull and close >= sdMid', source)
        self.assertIn('bool dominantTrendShort = dayRangeClear and dtpBear and close <= sdMid', source)
        self.assertIn('bool trendLongContext = strongStructTrendLong or dominantTrendLong', source)
        self.assertIn('bool trendShortContext = strongStructTrendShort or dominantTrendShort', source)
        self.assertIn('enableRegimePriority = input.bool(true, "Enable regime priority"', source)
        self.assertIn('trendPullbackBandAtr = input.float(0.35, "Trend pullback band (x ATR)"', source)
        self.assertIn('trendRejectClosePosLongMin = input.float(0.55, "Trend long reject close position min"', source)
        self.assertIn('trendRejectClosePosShortMax = input.float(0.45, "Trend short reject close position max"', source)
        self.assertIn('float trendSupportStructureBasis = trendLongContext ? todayStructLow : na', source)
        self.assertIn('float trendSupportPullbackBasis = trendLongContext ? levellib.nearestBelow(close + trendPullbackBand', source)
        self.assertIn('bool trendSupportUsesPullback = trendSupportPullbackReject', source)
        self.assertIn('float trendSupportBasis = trendSupportUsesPullback ? trendSupportPullbackBasis : trendSupportStructureBasis', source)
        self.assertIn('string trendSupportEntrySource = trendSupportUsesPullback ?', source)
        self.assertIn('float trendResistanceStructureBasis = trendShortContext ? todayStructHigh : na', source)
        self.assertIn('float trendResistancePullbackBasis = trendShortContext ? levellib.nearestAbove(close - trendPullbackBand', source)
        self.assertIn('bool trendResistanceUsesPullback = trendResistancePullbackReject', source)
        self.assertIn('float trendResistanceBasis = trendResistanceUsesPullback ? trendResistancePullbackBasis : trendResistanceStructureBasis', source)
        self.assertIn('string trendResistanceEntrySource = trendResistanceUsesPullback ?', source)
        self.assertIn('strongTrendSupport = trendLongContext and dayRangeClear and trendSupportAgeBars >= minTrendSupportAgeBars', source)
        self.assertIn('strongTrendResistance = trendShortContext and dayRangeClear and trendResistanceAgeBars >= minTrendSupportAgeBars', source)
        self.assertNotIn('strongTrendSupport = trendLongContext and dayRangeClear and trendSupportAgeBars >= minTrendSupportAgeBars and trendSupportCount >= minConfluenceCount', source)
        self.assertNotIn('strongTrendResistance = trendShortContext and dayRangeClear and trendResistanceAgeBars >= minTrendSupportAgeBars and trendResistanceCount >= minConfluenceCount', source)
        self.assertIn('bool trendLongPredictContext = trendLongContext and strongTrendSupport and trendLongPredictEntry', source)
        self.assertIn('bool trendLongConfirmContext = trendLongContext and strongTrendSupport and low <= trendSupportZoneHigh + trendPullbackBand', source)
        self.assertIn('bool trendShortPredictContext = trendShortContext and strongTrendResistance and trendShortPredictEntry', source)
        self.assertIn('bool trendShortConfirmContext = trendShortContext and strongTrendResistance and high >= trendResistanceZoneLow - trendPullbackBand', source)
        self.assertIn('trendLongPredictStop = strongTrendSupport ? trendSupportZoneLow - invalidationBuffer', source)
        self.assertIn('trendShortPredictStop = strongTrendResistance ? trendResistanceZoneHigh + invalidationBuffer', source)

    def test_probe_entries_support_predictive_and_confirmed_2b_orders(self):
        source = self.source
        display = self.display_source

        for text in (source, display):
            self.assertIn('structureClusterBandAtr = input.float(0.40, "Structure cluster band (x ATR)"', text)
            self.assertIn('minStructureSeparationAtr = input.float(1.00, "Independent structure separation (x ATR)"', text)
            self.assertIn('minMiddleSwingAtr = input.float(1.00, "Middle swing for second test (x ATR)"', text)
            self.assertIn('maxRetestAfterMiddleSwingBars = input.int(12, "Max bars after middle swing retest"', text)
            self.assertIn('probeLocalLegLookbackBars = input.int(30, "Local M leg lookback bars"', text)
            self.assertIn('minVisualMiddleRetraceRatio = input.float(0.35, "Visual middle retrace ratio"', text)
            self.assertIn('minVisualRightRetestRatio = input.float(0.65, "Visual right retest ratio"', text)
            self.assertIn('minVisualLegBps = input.float(12.0, "Visual min leg (bps)"', text)
            self.assertIn('minClearDayRangeAtr = input.float(2.20, "Clear day range (x ATR)"', text)
            self.assertIn('minTrendSupportAgeBars = input.int(4, "Trend support min age bars"', text)
            self.assertIn('exhaustionVolumeMaxRatio = input.float(1.05, "Exhaustion max volume (x MA)"', text)
            self.assertIn('momentumDecayMaxRatio = input.float(0.65, "Momentum decay max ratio"', text)
            self.assertIn('exhaustionDecayConfirmBars = input.int(2, "Momentum decay confirm bars"', text)
            self.assertIn('exhaustionClosePosShortMax = input.float(0.45, "Short exhaustion close position max"', text)
            self.assertIn('exhaustionClosePosLongMin = input.float(0.55, "Long exhaustion close position min"', text)
            self.assertIn('minAnyPlanGapBars = input.int(4, "Any-plan min gap bars"', text)
            self.assertIn('minAnyPlanDistanceAtr = input.float(0.80, "Any-plan min distance (x ATR)"', text)
            self.assertIn('volumeMaLen = input.int(20, "Volume MA length"', text)
            self.assertIn('highAttackVolumeMult = input.float(1.35, "High attack volume (x MA)"', text)
            self.assertIn('lowRetestVolumeMult = input.float(0.95, "Low retest volume (x MA)"', text)
            self.assertIn('attackClosePosThreshold = input.float(0.65, "Attack close position"', text)
            self.assertIn('attackVolumeCooldownBars = input.int(4, "Attack volume cooldown bars"', text)
            self.assertIn('minSameSideSignalSeparationAtr = input.float(1.20, "Same-side signal separation (x ATR)"', text)
            self.assertIn('failedBreakCloseBackAtr = input.float(0.10, "Failed break close-back (x ATR)"', text)
            self.assertIn('failedBreakConfirmBars = input.int(3, "Failed break confirm bars"', text)
            self.assertIn('weakNewExtremeMaxExtendAtr = input.float(0.60, "Weak new extreme max extension (x ATR)"', text)
            self.assertIn('weakNewExtremeMaxVolumeRatio = input.float(1.05, "Weak new extreme max volume (x MA)"', text)
            self.assertIn('weakNewExtremeVolumeDropRatio = input.float(0.75, "Weak new extreme volume drop vs attack"', text)
            self.assertIn('weakNewExtremeCloseBackAtr = input.float(0.10, "Weak new extreme close back (x ATR)"', text)
            self.assertIn('weakNewExtremeConfirmBars = input.int(3, "Weak new extreme confirm bars"', text)
            self.assertIn('distributionDropVolumeMult = input.float(1.20, "Distribution/accumulation volume (x MA)"', text)
            self.assertIn('distributionDropClosePosMax = input.float(0.45, "Distribution close position max"', text)
            self.assertIn('distributionDropMaxDistanceAtr = input.float(0.80, "Distribution max distance (x ATR)"', text)
            self.assertIn('structureBreakAcceptBars = input.int(3, "Structure break accept bars"', text)
            self.assertIn('structureBreakAcceptCloseAtr = input.float(0.15, "Structure break accept close (x ATR)"', text)
            self.assertIn('var bool upperBreakAcceptedRegime = false', text)
            self.assertIn('var bool lowerBreakAcceptedRegime = false', text)
            self.assertIn('var float lastAttackUpVolume = na', text)
            self.assertIn('var float lastAttackDownVolume = na', text)
            self.assertIn('var int lastWeakNewHighBar = na', text)
            self.assertIn('var float lastWeakNewHighLow = na', text)
            self.assertIn('var int lastTopVolumeClimaxBar = na', text)
            self.assertIn('var float lastTopVolumeClimaxHigh = na', text)
            self.assertIn('var float lastTopVolumeClimaxLow = na', text)
            self.assertIn('var float lastTopVolumeClimaxBase = na', text)
            self.assertIn('var float lastTopVolumeClimaxVolumeRatio = na', text)
            self.assertIn('var int lastTopFailureWatchBar = na', text)
            self.assertIn('var float lastTopFailureWatchHigh = na', text)
            self.assertIn('var float lastTopFailureWatchLow = na', text)
            self.assertIn('var float lastTopFailureWatchBase = na', text)
            self.assertIn('var int topProbeCycleId = 0', text)
            self.assertIn('var bool topProbeCycleActive = false', text)
            self.assertIn('var bool topProbeCycleConsumed = false', text)
            self.assertIn('var int topProbeCycleTouchBar = na', text)
            self.assertIn('var bool topPullbackArmed = false', text)
            self.assertIn('var int topPullbackArmedBar = na', text)
            self.assertIn('var int topNoDemandStreak = 0', text)
            self.assertIn('var int lastTopNoDemandBar = na', text)
            self.assertIn('var float lastTopNoDemandHigh = na', text)
            self.assertIn('var float lastTopNoDemandLow = na', text)
            self.assertIn('var int lastWeakNewLowBar = na', text)
            self.assertIn('var float lastWeakNewLowHigh = na', text)
            self.assertIn('var int lastBottomFailureWatchBar = na', text)
            self.assertIn('var float lastBottomFailureWatchHigh = na', text)
            self.assertIn('var float lastBottomFailureWatchLow = na', text)
            self.assertIn('var float lastBottomFailureWatchBase = na', text)
            self.assertIn('var int bottomProbeCycleId = 0', text)
            self.assertIn('var bool bottomProbeCycleActive = false', text)
            self.assertIn('var bool bottomProbeCycleConsumed = false', text)
            self.assertIn('var int bottomProbeCycleTouchBar = na', text)
            self.assertIn('var bool bottomPullbackArmed = false', text)
            self.assertIn('var int bottomPullbackArmedBar = na', text)
            self.assertIn('var int bottomNoSupplyStreak = 0', text)
            self.assertIn('var int lastBottomNoSupplyBar = na', text)
            self.assertIn('var float lastBottomNoSupplyHigh = na', text)
            self.assertIn('var float lastBottomNoSupplyLow = na', text)
            self.assertIn('var int lastTopSweepBar = na', text)
            self.assertIn('var bool lastTopSweepVolumeAttack = false', text)
            self.assertIn('var int lastBottomSweepBar = na', text)
            self.assertIn('var bool lastBottomSweepVolumeAttack = false', text)
            self.assertIn('upperBreakAcceptedRegime := true', text)
            self.assertIn('lowerBreakAcceptedRegime := true', text)
            self.assertIn('upperBreakExt = upperBreakAcceptedRegime', text)
            self.assertIn('lowerBreakExt = lowerBreakAcceptedRegime', text)
            self.assertIn('todayStructHighZoneLow', text)
            self.assertIn('todayStructLowZoneHigh', text)
            self.assertIn('lowBeforeStructHigh', text)
            self.assertIn('highBeforeStructLow', text)
            self.assertIn('lowSinceStructHighBar', text)
            self.assertIn('highSinceStructLowBar', text)
            self.assertIn('risklib.visualLegBps(', text)
            self.assertIn('risklib.visualLegRatio(', text)
            self.assertIn('volumeRatio = not na(volumeMa) and volumeMa > 0.0 ? barVolume / volumeMa : 1.0', text)
            self.assertIn('volumeAttackUp = volumeExpanded and close > open and closePosition >= attackClosePosThreshold', text)
            self.assertIn('volumeAttackDown = volumeExpanded and close < open and closePosition <= 1.0 - attackClosePosThreshold', text)
            self.assertIn('"left_leg_too_small"', text)
            self.assertIn('"middle_leg_too_small"', text)
            self.assertIn('"right_retest_too_small"', text)
            self.assertIn('"low_volume_retest_ok"', text)
            self.assertIn('"high_volume_failed_break_ok"', text)
            self.assertIn('"recent_failed_break"', text)
            self.assertIn('"weak_new_high_confirmed"', text)
            self.assertIn('"weak_new_low_confirmed"', text)
            self.assertIn('"distribution_drop_confirmed"', text)
            self.assertIn('"accumulation_rise_confirmed"', text)
            self.assertIn('"volume_climax_failed_break_short"', text)
            self.assertIn('"volume_climax_failed_break_confirmed"', text)
            self.assertIn('"naked_high_volume_reversal_short"', text)
            self.assertIn('"naked_high_volume_reversal_confirmed"', text)
            self.assertIn('"naked_high_immediate_reversal_short"', text)
            self.assertIn('"naked_high_immediate_reversal_confirmed"', text)
            self.assertIn('"naked_high_decay_break_short"', text)
            self.assertIn('"naked_high_decay_break_confirmed"', text)
            self.assertIn('"naked_low_volume_reversal_long"', text)
            self.assertIn('"naked_low_volume_reversal_confirmed"', text)
            self.assertIn('"naked_low_decay_break_long"', text)
            self.assertIn('"naked_low_decay_break_confirmed"', text)
            self.assertIn('"new_high_volume_climax_failed"', text)
            self.assertIn('"naked_high_volume_reversal"', text)
            self.assertIn('"naked_high_decay_break"', text)
            self.assertIn('"naked_low_volume_reversal"', text)
            self.assertIn('"naked_low_decay_break"', text)
            self.assertIn('"low_volume_momentum_decay_ok"', text)
            self.assertIn('"day_range_not_formed"', text)
            self.assertIn('"momentum_not_decayed"', text)
            self.assertIn('"momentum_decay_not_continuous"', text)
            self.assertIn('"no_weak_close_confirm"', text)
            self.assertIn('"pullback_not_enough"', text)
            self.assertIn('"micro_structure_too_close"', text)
            self.assertNotIn('"volume_attack_up_no_short"', text)
            self.assertNotIn('"volume_attack_down_no_long"', text)

        self.assertIn('topPredictAllowed = topPredictContext and risklib.smallStopTrialAllowed(-1', source)
        self.assertIn('bottomPredictAllowed = bottomPredictContext and risklib.smallStopTrialAllowed(1', source)
        self.assertIn('float topBasis = todayStructHigh', source)
        self.assertIn('float bottomBasis = todayStructLow', source)
        self.assertIn('strongTopProbeZone = not na(todayStructHigh) and not na(topZoneLow) and not na(topZoneHigh)', source)
        self.assertIn('strongBottomProbeZone = not na(todayStructLow) and not na(bottomZoneLow) and not na(bottomZoneHigh)', source)
        self.assertNotIn('strongTopProbeZone = topCount >= minConfluenceCount', source)
        self.assertNotIn('strongBottomProbeZone = bottomCount >= minConfluenceCount', source)
        self.assertIn('topSweptStructure = confirmed and topRightShoulder and high > topZoneHigh + tickBuffer', source)
        self.assertIn('topRecentSweepFailed = confirmed and not topDirectSweepFailed and recentTopSweepWindow and close < topZoneHigh - atr * failedBreakCloseBackAtr and upperWeakClose', source)
        self.assertIn('topSweepFailed = topDirectSweepFailed or topRecentSweepFailed', source)
        self.assertIn('probeStrictTouchToleranceAtr = input.float(0.05, "Probe strict touch tolerance (x ATR)"', source)
        self.assertIn('topStructuralRetestLevel = upperBreakAcceptedRegime and not na(prevStructHigh) ? prevStructHigh : topBasis', source)
        self.assertIn('topStrictRetestTouch = not na(topStructuralRetestLevel) and high >= topStructuralRetestLevel - strictRetestTolerance', source)
        self.assertIn('topWeakBase = topStructuralRetestLevel', source)
        self.assertIn('topWeakStructureReady = strongTopProbeZone and topAnchorReady and topRetestBand', source)
        self.assertIn('topVolumeClimaxStructureReady = strongTopProbeZone and topPullbackArmed and topRetestBand', source)
        self.assertIn('recentTopVolumeClimaxWindow = not na(barsSinceTopVolumeClimax) and barsSinceTopVolumeClimax > 0.0 and barsSinceTopVolumeClimax <= failedBreakConfirmBars', source)
        self.assertIn('topVolumeClimaxCloseBack = not na(lastTopVolumeClimaxBase) and close <= lastTopVolumeClimaxBase + atr * failedBreakCloseBackAtr', source)
        self.assertIn('topVolumeClimaxRedCandle = close < open', source)
        self.assertIn('topVolumeClimaxAttackEvent = confirmed and dayRangeClear and topVolumeClimaxStructureReady', source)
        self.assertIn('topVolumeClimaxFailedBreakConfirmed = confirmed and recentTopVolumeClimaxWindow and topVolumeClimaxRedCandle', source)
        self.assertIn('topWeakNewHighEvent = confirmed and dayRangeClear and topWeakStructureReady', source)
        self.assertIn('topWeakNewHighWatch = topWeakNewHighEvent and topWeakVolumeQuiet and topWeakVolumeDropped and topMomentumDecayed', source)
        self.assertIn('topWeakNewHighConfirmed = topWeakNewHighWatch and (topWeakCloseBack or upperWeakClose)', source)
        self.assertIn('topDistributionDropConfirmed = confirmed and recentWeakNewHighWindow and volumeRatio >= distributionDropVolumeMult', source)
        self.assertIn('recentTopFailureWatchWindow = not na(barsSinceTopFailureWatch) and barsSinceTopFailureWatch > 0.0 and barsSinceTopFailureWatch <= failedBreakConfirmBars', source)
        self.assertIn('topFailureWatchActive = not na(barsSinceTopFailureWatch) and barsSinceTopFailureWatch > 0.0', source)
        self.assertIn('var bool lastTopFailureWatchVolumeProbe = false', source)
        self.assertIn('lastTopFailureWatchVolumeProbe := true', source)
        self.assertIn('topHighVolumeDropConfirmed = confirmed and topPullbackArmed and topFailureWatchActive and lastTopFailureWatchVolumeProbe', source)
        self.assertIn('topNakedTouchEvent = confirmed and dayRangeClear', source)
        self.assertIn('topHighVolumeProbeWatch = confirmed and topPullbackArmed and topFailureWatchActive', source)
        self.assertIn('topRetestTouchNow = confirmed and topPullbackArmed and topFailureWatchActive', source)
        self.assertIn('topNoDemandWatch = topRetestTouchNow and not topHighVolumeDropConfirmed and volumeRatio < distributionDropVolumeMult', source)
        self.assertIn('topNoDemandBreakImmediateRaw = topNoDemandWatch and topNoDemandRsiProof', source)
        self.assertIn('topNoDemandBreakImmediate = allowSameBarWeakConfirm and topNoDemandBreakImmediateRaw', source)
        self.assertIn('topNoDemandBreakDelayed = confirmed and topPullbackArmed and recentTopNoDemandWindow and topNoDemandStreak >= 2', source)
        self.assertIn('topNoDemandBreakConfirmed = topNoDemandBreakImmediate or topNoDemandBreakDelayed', source)
        self.assertIn('close <= lastTopFailureWatchBase - atr * failedBreakCloseBackAtr', source)
        self.assertIn('bottomSweptStructure = confirmed and bottomRightShoulder and low < bottomZoneLow - tickBuffer', source)
        self.assertIn('bottomRecentSweepFailed = confirmed and not bottomDirectSweepFailed and recentBottomSweepWindow and close > bottomZoneLow + atr * failedBreakCloseBackAtr and lowerStrongClose', source)
        self.assertIn('bottomSweepFailed = bottomDirectSweepFailed or bottomRecentSweepFailed', source)
        self.assertIn('bottomStructuralRetestLevel = lowerBreakAcceptedRegime and not na(prevStructLow) ? prevStructLow : bottomBasis', source)
        self.assertIn('bottomStrictRetestTouch = not na(bottomStructuralRetestLevel) and low <= bottomStructuralRetestLevel + strictRetestTolerance', source)
        self.assertIn('bottomWeakBase = bottomStructuralRetestLevel', source)
        self.assertIn('bottomWeakStructureReady = strongBottomProbeZone and bottomAnchorReady and bottomRetestBand', source)
        self.assertIn('bottomWeakNewLowEvent = confirmed and dayRangeClear and bottomWeakStructureReady', source)
        self.assertIn('bottomWeakNewLowWatch = bottomWeakNewLowEvent and bottomWeakVolumeQuiet and bottomWeakVolumeDropped and bottomMomentumDecayed', source)
        self.assertIn('bottomWeakNewLowConfirmed = bottomWeakNewLowWatch and (bottomWeakCloseBack or lowerStrongClose)', source)
        self.assertIn('bottomAccumulationRiseConfirmed = confirmed and recentWeakNewLowWindow and volumeRatio >= distributionDropVolumeMult', source)
        self.assertIn('recentBottomFailureWatchWindow = not na(barsSinceBottomFailureWatch) and barsSinceBottomFailureWatch > 0.0 and barsSinceBottomFailureWatch <= failedBreakConfirmBars', source)
        self.assertIn('var bool lastBottomFailureWatchVolumeProbe = false', source)
        self.assertIn('lastBottomFailureWatchVolumeProbe := true', source)
        self.assertIn('bottomHighVolumeRiseConfirmed = confirmed and bottomPullbackArmed and recentBottomFailureWatchWindow and lastBottomFailureWatchVolumeProbe', source)
        self.assertIn('bottomNakedTouchEvent = confirmed and dayRangeClear', source)
        self.assertIn('bottomHighVolumeProbeWatch = confirmed and bottomPullbackArmed and recentBottomFailureWatchWindow', source)
        self.assertIn('bottomRetestTouchNow = confirmed and bottomPullbackArmed and recentBottomFailureWatchWindow', source)
        self.assertIn('bottomNoSupplyWatch = bottomRetestTouchNow and not bottomHighVolumeRiseConfirmed and volumeRatio < distributionDropVolumeMult', source)
        self.assertIn('bottomNoSupplyBreakImmediateRaw = bottomNoSupplyWatch and bottomNoSupplyRsiProof', source)
        self.assertIn('bottomNoSupplyBreakImmediate = allowSameBarWeakConfirm and bottomNoSupplyBreakImmediateRaw', source)
        self.assertIn('bottomNoSupplyBreakDelayed = confirmed and bottomPullbackArmed and recentBottomNoSupplyWindow and bottomNoSupplyStreak >= 2', source)
        self.assertIn('bottomNoSupplyBreakConfirmed = bottomNoSupplyBreakImmediate or bottomNoSupplyBreakDelayed', source)
        self.assertIn('close >= lastBottomFailureWatchBase + atr * failedBreakCloseBackAtr', source)
        self.assertIn('topLeftLegBps = risklib.visualLegBps(topLeftLeg, todayStructHigh)', source)
        self.assertIn('topGlobalMiddleRetraceRatio = risklib.visualLegRatio(topMiddleLeg, topLeftLeg)', source)
        self.assertIn('topLocalMiddleRetraceRatio = risklib.visualLegRatio(topMiddleLeg, topLocalLeftLeg)', source)
        self.assertIn('topMiddleRetraceRatio = not na(topLocalMiddleRetraceRatio) ? topLocalMiddleRetraceRatio : topGlobalMiddleRetraceRatio', source)
        self.assertIn('topRightRetestRatio = risklib.visualLegRatio(topRightLeg, topMiddleLeg)', source)
        self.assertIn('topLargePullbackReady = not na(topMiddleLeg) and topMiddleLeg >= atr * minMiddleSwingAtr and topMiddleRetraceRatio >= minVisualMiddleRetraceRatio', source)
        self.assertIn('topPullbackArmedEvent = confirmed and dayRangeClear and strongTopProbeZone and topVisualLeftOk and topLargePullbackReady and not topPullbackArmed', source)
        self.assertIn('topPullbackArmed := true', source)
        self.assertIn('topImmediatePullbackWatch = topPullbackArmedEvent and topRetestBand and topStrictRetestTouch and close < open', source)
        self.assertIn('topImmediatePullbackShort = allowSameBarWeakConfirm and topImmediatePullbackWatch', source)
        self.assertIn('topMiddleSwingReady = not na(lowSinceStructHighBar) and topVisualLeftOk and topMiddleRetraceRatio >= minVisualMiddleRetraceRatio', source)
        self.assertIn('topRightRetestReady = topMiddleSwingReady and topRightRetestRatio >= minVisualRightRetestRatio', source)
        self.assertIn('topRetestFastEnough = topRightRetestReady and bar_index > lowSinceStructHighBar and bar_index - lowSinceStructHighBar <= maxRetestAfterMiddleSwingBars', source)
        self.assertIn('topAnchorReady = dayRangeClear and topAnchorAgeBars >= probeMinAnchorAgeBars and topPullbackArmed', source)
        self.assertIn('topMomentumDecayRatio = not na(topMiddleSpeed) and topMiddleSpeed > 0.0 ? topRightSpeed / topMiddleSpeed : na', source)
        self.assertIn('topDecayStreak := topRightShoulder and topRetestBand and upperNoVolumeExpansion and topMomentumDecayed ? topDecayStreak + 1 : 0', source)
        self.assertIn('bool topMomentumDecayReady = topDecayStreak >= exhaustionDecayConfirmBars', source)
        self.assertIn('upperExhaustionZone = dayRangeClear and topRightShoulder and topRetestBand and upperNoVolumeExpansion and topMomentumDecayReady', source)
        self.assertIn('upperExhaustionConfirmedShort = confirmed and upperExhaustionZone and upperWeakClose', source)
        self.assertIn('topHighVolumeFailedBreak = topSweepFailed and (volumeExpanded or lastTopSweepVolumeAttack)', source)
        self.assertIn('topPredictVolumeOk = true', source)
        self.assertIn('topNakedFailureShort = confirmed and topPullbackArmed and topFailureWatchActive', source)
        self.assertIn('topImmediateReversalShort = topImmediatePullbackShort or topNakedFailureShort', source)
        self.assertIn('topFailureRepeatShort = topVolumeClimaxFailedBreakConfirmed or topHighVolumeDropConfirmed or topNoDemandBreakConfirmed or topImmediateReversalShort', source)
        self.assertIn('topConfirmedShort = topSweepFailed or upperExhaustionConfirmedShort or topWeakNewHighConfirmed or topDistributionDropConfirmed or topVolumeClimaxFailedBreakConfirmed or topHighVolumeDropConfirmed or topNoDemandBreakConfirmed or topImmediateReversalShort', source)
        self.assertIn('if topVolumeClimaxFailedBreakConfirmed', source)
        self.assertIn('topProbePattern := "volume_climax_failed_break_short"', source)
        self.assertIn('topProbePattern := "naked_high_volume_reversal_short"', source)
        self.assertIn('topProbePattern := "naked_high_immediate_reversal_short"', source)
        self.assertIn('topConfirmVolumeOk = topSweepFailed or topImmediateReversalShort or topHighVolumeDropConfirmed or topNoDemandBreakConfirmed or topHighVolumeFailedBreak or upperExhaustionConfirmedShort or topWeakNewHighConfirmed or topDistributionDropConfirmed or topVolumeClimaxFailedBreakConfirmed', source)
        self.assertIn('topCloseLimitShort = topVolumeClimaxFailedBreakConfirmed or topHighVolumeDropConfirmed or topNoDemandBreakConfirmed or topImmediateReversalShort', source)
        self.assertIn('topProbeCycleTouchNow = topImmediatePullbackWatch or topSweptStructure or topNakedTouchEvent or topVolumeClimaxAttackEvent or topWeakNewHighEvent or topHighVolumeProbeWatch or topNoDemandWatch or upperExhaustionZone', source)
        self.assertIn('if topProbeCycleTouchNow and not topProbeCycleActive', source)
        self.assertIn('topConfirmGapOk = topSignalGapOk or topFailureRepeatShort', source)
        self.assertIn('topConfirmEntryRaw = topConfirmedShort ? (topVolumeClimaxFailedBreakConfirmed ? topClimaxRetestEntry : topCloseLimitShort ? topFailureRetestEntry', source)
        self.assertIn('topPriorHighStop = math.max(nz(topStructuralRetestLevel, high), nz(topZoneHigh, high)) + invalidationBuffer', source)
        self.assertIn('topFailureWatchStop = risklib.looserStop(math.max(nz(lastTopFailureWatchHigh, high), high) + invalidationBuffer, topPriorHighStop, -1)', source)
        self.assertIn('topConfirmEntry = topConfirmedShort ? stopBoundedEntry(-1, topCloseLimitShort ? topConfirmEntryRaw : scalpLimitEntry(-1, close, topBasis, topConfirmEntryRaw, atr, scalpLimitOffsetAtr), topConfirmStop', source)
        self.assertIn('topNoDemandBreakConfirmed ? topNoDemandStop', source)
        self.assertIn('topHighVolumeDropConfirmed or topImmediateReversalShort ? topFailureWatchStop', source)
        self.assertIn('topPredictContext = (topFirstExhaustion or topRightShoulder) and topCounterTrendAllowed and topPredictEntry >= close and topPredictEntry - close <= atr * predictionArmDistanceAtr and topSignalGapOk and topPredictVolumeOk', source)
        self.assertIn('topHasCountertrendEvidence = upperExhaustionConfirmedShort or topWeakNewHighConfirmed or topDistributionDropConfirmed or topFailureRepeatShort', source)
        self.assertIn('topCountertrendBlockReason = modellib.topCountertrendBlockReason(', source)
        self.assertIn('topCountertrendOverrideOk = trendBullPriority and topCountertrendBlockReason == "passed"', source)
        self.assertIn('topConfirmContext = topConfirmedShort and (topCounterTrendAllowed or topCountertrendOverrideOk) and topConfirmGapOk and topConfirmVolumeOk', source)
        self.assertIn('bottomLeftLegBps = risklib.visualLegBps(bottomLeftLeg, todayStructLow)', source)
        self.assertIn('bottomGlobalMiddleRetraceRatio = risklib.visualLegRatio(bottomMiddleLeg, bottomLeftLeg)', source)
        self.assertIn('bottomLocalMiddleRetraceRatio = risklib.visualLegRatio(bottomMiddleLeg, bottomLocalLeftLeg)', source)
        self.assertIn('bottomMiddleRetraceRatio = not na(bottomLocalMiddleRetraceRatio) ? bottomLocalMiddleRetraceRatio : bottomGlobalMiddleRetraceRatio', source)
        self.assertIn('bottomRightRetestRatio = risklib.visualLegRatio(bottomRightLeg, bottomMiddleLeg)', source)
        self.assertIn('bottomLargePullbackReady = not na(bottomMiddleLeg) and bottomMiddleLeg >= atr * minMiddleSwingAtr and bottomMiddleRetraceRatio >= minVisualMiddleRetraceRatio', source)
        self.assertIn('bottomPullbackArmedEvent = confirmed and dayRangeClear and strongBottomProbeZone and bottomVisualLeftOk and bottomLargePullbackReady and not bottomPullbackArmed', source)
        self.assertIn('bottomPullbackArmed := true', source)
        self.assertIn('bottomMiddleSwingReady = not na(highSinceStructLowBar) and bottomVisualLeftOk and bottomMiddleRetraceRatio >= minVisualMiddleRetraceRatio', source)
        self.assertIn('bottomRightRetestReady = bottomMiddleSwingReady and bottomRightRetestRatio >= minVisualRightRetestRatio', source)
        self.assertIn('bottomRetestFastEnough = bottomRightRetestReady and bar_index > highSinceStructLowBar and bar_index - highSinceStructLowBar <= maxRetestAfterMiddleSwingBars', source)
        self.assertIn('bottomAnchorReady = dayRangeClear and bottomAnchorAgeBars >= probeMinAnchorAgeBars and bottomPullbackArmed', source)
        self.assertIn('bottomMomentumDecayRatio = not na(bottomMiddleSpeed) and bottomMiddleSpeed > 0.0 ? bottomRightSpeed / bottomMiddleSpeed : na', source)
        self.assertIn('bottomDecayStreak := bottomRightShoulder and bottomRetestBand and lowerNoVolumeExpansion and bottomMomentumDecayed ? bottomDecayStreak + 1 : 0', source)
        self.assertIn('bool bottomMomentumDecayReady = bottomDecayStreak >= exhaustionDecayConfirmBars', source)
        self.assertIn('lowerExhaustionZone = dayRangeClear and bottomRightShoulder and bottomRetestBand and lowerNoVolumeExpansion and bottomMomentumDecayReady', source)
        self.assertIn('lowerExhaustionConfirmedLong = confirmed and lowerExhaustionZone and lowerStrongClose', source)
        self.assertIn('bottomHighVolumeFailedBreak = bottomSweepFailed and (volumeExpanded or lastBottomSweepVolumeAttack)', source)
        self.assertIn('bottomPredictVolumeOk = true', source)
        self.assertIn('bottomConfirmedLong = bottomSweepFailed or lowerExhaustionConfirmedLong or bottomWeakNewLowConfirmed or bottomAccumulationRiseConfirmed or bottomHighVolumeRiseConfirmed or bottomNoSupplyBreakConfirmed', source)
        self.assertIn('bottomProbeCycleTouchNow = bottomSweptStructure or bottomNakedTouchEvent or bottomWeakNewLowEvent or bottomHighVolumeProbeWatch or bottomNoSupplyWatch or lowerExhaustionZone', source)
        self.assertIn('if bottomProbeCycleTouchNow and not bottomProbeCycleActive', source)
        self.assertIn('bottomConfirmVolumeOk = bottomSweepFailed or bottomHighVolumeRiseConfirmed or bottomNoSupplyBreakConfirmed or bottomHighVolumeFailedBreak or lowerExhaustionConfirmedLong or bottomWeakNewLowConfirmed or bottomAccumulationRiseConfirmed', source)
        self.assertIn('bottomPriorLowStop = math.min(nz(bottomStructuralRetestLevel, low), nz(bottomZoneLow, low)) - invalidationBuffer', source)
        self.assertIn('bottomFailureWatchStop = risklib.looserStop(math.min(nz(lastBottomFailureWatchLow, low), low) - invalidationBuffer, bottomPriorLowStop, 1)', source)
        self.assertIn('bottomPredictContext = (bottomFirstExhaustion or bottomRightShoulder) and bottomCounterTrendAllowed and bottomPredictEntry <= close and close - bottomPredictEntry <= atr * predictionArmDistanceAtr and bottomSignalGapOk and bottomPredictVolumeOk', source)
        self.assertIn('bottomHasCountertrendEvidence = lowerExhaustionConfirmedLong or bottomWeakNewLowConfirmed or bottomAccumulationRiseConfirmed or bottomHighVolumeRiseConfirmed or bottomNoSupplyBreakConfirmed', source)
        self.assertIn('bottomCountertrendBlockReason = modellib.bottomCountertrendBlockReason(', source)
        self.assertIn('bottomCountertrendOverrideOk = trendBearPriority and bottomCountertrendBlockReason == "passed"', source)
        self.assertIn('bottomConfirmContext = bottomConfirmedLong and (bottomCounterTrendAllowed or bottomCountertrendOverrideOk) and bottomSignalGapOk and bottomConfirmVolumeOk', source)
        self.assertIn('lastVolumeAttackUpBar := bar_index', source)
        self.assertIn('lastAttackUpVolume := barVolume', source)
        self.assertIn('lastVolumeAttackDownBar := bar_index', source)
        self.assertIn('lastAttackDownVolume := barVolume', source)
        self.assertIn('attackUpCooling = not na(barsSinceAttackUp) and barsSinceAttackUp <= attackVolumeCooldownBars', source)
        self.assertIn('confirmed and todayHigh > todayStructHigh + tickBuffer', source)
        self.assertIn('breakoutHighZoneHigh := na(breakoutHighZoneHigh) ? todayStructHighZoneHigh : breakoutHighZoneHigh', source)
        self.assertIn('upperBreakAccepting = not na(breakoutHighZoneHigh) and not na(todayStructLow) and close > breakoutHighZoneHigh + atr * structureBreakAcceptCloseAtr', source)
        self.assertIn('lowerBreakAccepting = not na(breakoutLowZoneLow) and not na(todayStructHigh) and close < breakoutLowZoneLow - atr * structureBreakAcceptCloseAtr', source)
        self.assertIn('upperStructureBreakAccepted := true', source)
        self.assertIn('lowerStructureBreakAccepted := true', source)
        self.assertIn('bool longActionable = trendLongConfirmNow or bottomConfirmAllowed', source)
        self.assertIn('bool shortActionable = trendShortConfirmNow or topConfirmAllowed', source)
        self.assertIn('string selectedEntryIntent = selectedDirection != 0 ? "confirmed_limit" : "none"', source)
        self.assertIn('string selectedTrialRiskMode = selectedDirection != 0 ? "full" : "none"', source)
        self.assertIn('float selectedRiskBudget = selectedDirection != 0 ? confirmedMaxRiskDollars : na', source)
        self.assertIn('string reason = "quick_ema_scalp_trial"', source)
        self.assertNotIn('predictive_small_stop_trial', source)
        self.assertIn('selectedSameSideSignalFarEnough', source)
        self.assertIn('selectedAnyPlanFarEnough', source)
        self.assertIn('probeMinAnchorAgeBars = input.int(6, "Probe min anchor age bars"', source)
        self.assertIn('probeMinPullbackAtr = input.float(0.80, "Probe min pullback (x ATR)"', source)
        self.assertIn('probeRetestBandAtr = input.float(0.35, "Probe retest band (x ATR)"', source)
        self.assertIn('topConfirmAllowed = topConfirmContext and risklib.smallStopTrialAllowed(-1', source)
        self.assertIn('bottomConfirmAllowed = bottomConfirmContext and risklib.smallStopTrialAllowed(1', source)
        self.assertIn('topSignalGapOk', source)
        self.assertIn('bottomSignalGapOk', source)

    def test_entry_window_uses_0940_to_1530(self):
        source = self.source
        display = self.display_source

        self.assertIn('tradingSession = input.session("0940-1530", "Trading session"', source)
        self.assertIn('entrySession = input.session("0940-1530", "Entry window"', source)
        self.assertIn('entrySession = input.session("0940-1530", "Entry window"', display)
        self.assertIn('jsonStr("entry_cutoff_time", "15:30")', source)

    def test_core_serializes_predictive_metadata_and_latency_fields(self):
        source = self.source

        for field in (
            'jsonStr("entry_intent", entryIntent)',
            'jsonStr("trial_risk_mode", trialRiskMode)',
            'jsonStr("trade_model", TRADE_MODEL)',
            'jsonBool("structure_clear", selectedStructureClear)',
            'jsonNum("structure_anchor_price", selectedStructureAnchor)',
            'jsonNum("expected_r", selectedExpectedR)',
            'jsonNum("tp_runner_gap_r", selectedTpRunnerGapR)',
            'jsonNum("min_tp_runner_gap_r", minTpRunnerGapR)',
            'jsonBool("same_bar_runner_allowed", allowSameBarRunnerAfterFill)',
            'jsonStr("trend_struct_dir", trendStructDir)',
            'jsonStr("trend_struct_pattern", selectedTrendStructPattern)',
            'jsonStr("trend_regime", trendRegime)',
            'jsonStr("market_regime", marketRegime)',
            'jsonStr("dominant_trend_side", dominantTrendSide)',
            'jsonStr("trade_family", selectedTradeFamily)',
            'jsonStr("trend_entry_source", selectedTrendEntrySource)',
            'jsonBool("regime_priority_enabled", enableRegimePriority)',
            'jsonBool("countertrend_reclaim_ok", selectedCountertrendReclaimOk)',
            'jsonStr("countertrend_block_reason", selectedCountertrendBlockReason)',
            'jsonBool("trend_plus_reversion_confluence", trendPlusReversionConfluence)',
            'jsonStr("model_conflict_reason", modelConflictReason)',
            'jsonBool("day_range_formed", dayRangeFormed)',
            'jsonNum("day_range_atr", dayRangeAtr)',
            'jsonStr("level_role", selectedLevelRole)',
            'jsonStr("exhaustion_side", selectedExhaustionSide)',
            'jsonBool("exhaustion_confirmed", selectedExhaustionConfirmed)',
            'jsonStr("exhaustion_reason", selectedExhaustionReason)',
            'jsonNum("momentum_decay_ratio", selectedMomentumDecayRatio)',
            'jsonNum("momentum_decay_streak", selectedMomentumDecayStreak)',
            'jsonNum("momentum_decay_confirm_bars", selectedMomentumDecayConfirmBars)',
            'jsonBool("attack_volume_cooling", selectedAttackVolumeCooling)',
            'jsonNum("attack_volume_cooldown_bars", selectedAttackVolumeCooldownBars)',
            'jsonBool("structure_break_accepted", selectedStructureBreakAccepted)',
            'jsonNum("structure_break_accept_bars", selectedStructureBreakAcceptBars)',
            'jsonNum("prior_level_distance_atr", selectedPriorLevelDistanceAtr)',
            'jsonNum("middle_retrace_ratio", selectedProbeMiddleRatio)',
            'jsonNum("right_retest_ratio", selectedProbeRightRatio)',
            'jsonNum("any_plan_gap_bars", selectedAnyPlanGapBars)',
            'jsonNum("any_plan_distance_atr", selectedAnyPlanDistanceAtr)',
            'jsonStr("probe_pattern", selectedProbePattern)',
            'jsonStr("probe_filter_reason", selectedProbeFilterReason)',
            'jsonNum("probe_retest_gap_bars", selectedProbeRetestGapBars)',
            'jsonNum("visual_left_leg_bps", selectedProbeLeftLegBps)',
            'jsonNum("visual_middle_retrace_ratio", selectedProbeMiddleRatio)',
            'jsonNum("visual_right_retest_ratio", selectedProbeRightRatio)',
            'jsonNum("volume_ratio", selectedVolumeRatio)',
            'jsonStr("volume_reason", selectedVolumeReason)',
            'jsonNum("close_position", selectedClosePosition)',
            'jsonBool("volume_attack_up", volumeAttackUp)',
            'jsonBool("volume_attack_down", volumeAttackDown)',
            'jsonNum("today_struct_high", todayStructHigh)',
            'jsonNum("today_struct_low", todayStructLow)',
            'jsonBool("small_stop_gate_passed", selectedSmallStopGatePassed)',
            'jsonStr("small_stop_gate_reason", selectedSmallStopGateReason)',
            'jsonNum("stop_distance_atr", selectedStopDistanceAtr)',
            'jsonNum("stop_distance_bps", selectedStopDistanceBps)',
            'jsonNum("max_trial_risk_dollars", selectedRiskBudget)',
            'jsonNum("prediction_level", selectedPredictionLevel)',
            'jsonNum("prediction_zone_low", selectedZoneLow)',
            'jsonNum("prediction_zone_high", selectedZoneHigh)',
            'jsonNum("invalidation_price", selectedInvalidation)',
            'jsonStr("main_reason", selectedMainReason)',
            'jsonStr("secondary_reason", selectedSecondaryReason == "" ? "none" : selectedSecondaryReason)',
            'jsonStr("plan_replace_reason", planReplaced ? replaceReason : "none")',
            'jsonNum("bar_open_ms", time)',
            'jsonNum("bar_close_ms", time_close)',
            'jsonNum("pine_eval_ms", timenow)',
        ):
            self.assertIn(field, source)

    def test_pending_lifecycle_replaces_or_cancels_unfilled_predictions(self):
        source = self.source

        self.assertIn('entryOrderTtlBars = input.int(3, "Entry order TTL bars"', source)
        self.assertIn('pendingExpired = pendingEntry and not na(activeExpiresBar) and bar_index > activeExpiresBar', source)
        self.assertIn('pendingInvalidated = pendingEntry and (activeDirection == 1 ? close < activeStop : close > activeStop)', source)
        self.assertIn('pendingOppositeSelected = pendingEntry and selectedDirection != 0 and selectedDirection != activeDirection and selectedStructureClear and selectedEntryNearAnchorOnly and selectedProbeCyclePassed and selectedRsiPassed', source)
        self.assertIn('pendingLostConfirmation = pendingEntry and activeEntryIntent != "confirmed_limit"', source)
        self.assertIn('"pending_lost_confirmation"', source)
        self.assertIn('"attack_volume_cooling_cancel"', source)
        self.assertIn('"structure_break_accepted_cancel"', source)
        self.assertIn('bool selectedPendingUpgrade = false', source)
        self.assertIn('planReplaceMinMoveAtr = input.float(0.60, "Plan replace min move (x ATR)"', source)
        self.assertIn('bool meaningfulPlanMove = math.abs(nz(activeEntry, selectedEntry) - selectedEntry) >= atr * planReplaceMinMoveAtr', source)
        self.assertIn('pendingSameDirectionReplace = false', source)
        self.assertIn('strategy.cancel(orderIdForDirection(activeDirection))', source)
        self.assertIn('"same_direction_plan_replaced"', source)
        self.assertIn('var int activeProbeCycleId = na', source)
        self.assertIn('activeProbeCycleId := selectedProbeSetup ? selectedProbeCycleId : na', source)
        self.assertIn('activeProbeCycleId := na', source)

    def test_quick_ema_scalp_uses_ema_target_rsi_filter_and_small_stop(self):
        source = self.source

        self.assertIn('scalpLimitOffsetAtr = input.float(0.10, "Scalp limit offset (x ATR)"', source)
        self.assertIn('scalpMaxEntryAwayAtr = input.float(0.35, "Scalp max entry distance from anchor (x ATR)"', source)
        self.assertIn('scalpBreakevenR = input.float(1.00, "Scalp breakeven trigger (R)"', source)
        self.assertIn('minTpRunnerGapR = input.float(0.50, "Minimum TP-runner gap (R)"', source)
        self.assertIn('allowSameBarWeakConfirm = input.bool(false, "Allow same-bar weak confirm"', source)
        self.assertIn('minInitialStopClearanceR = input.float(0.15, "Minimum initial stop clearance (R)"', source)
        self.assertIn('backtestDelayInitialRiskUntilNextBar = input.bool(true, "Backtest: delay initial risk until next bar"', source)
        self.assertIn('allowSameBarRunnerAfterFill = input.bool(false, "Allow same-bar runner after fill"', source)
        self.assertIn('scalpNoFollowBars = input.int(4, "Scalp no-follow bars"', source)
        self.assertIn('scalpLimitEntry(int direction, float currentClose, float anchorPrice, float fallbackEntry, float atrValue, float offsetAtr) =>', source)
        self.assertIn('risklib.scalpEmaTarget(', source)
        self.assertIn('float scalpRsi = ta.rsi(close, rsiLen)', source)
        self.assertIn('float scalpRsiSmooth = ta.ema(scalpRsi, rsiSmoothLen)', source)
        self.assertIn('bool scalpFastBearDiv = scalpRsiWasHigh', source)
        self.assertIn('bool scalpFastBullDiv = scalpRsiWasLow', source)
        self.assertIn('bool scalpRsiShortOk = scalpRsiWasHigh and (scalpRsiWeakening or scalpFastBearDiv)', source)
        self.assertIn('bool scalpRsiLongOk = scalpRsiWasLow and (scalpRsiStrengthening or scalpFastBullDiv)', source)
        self.assertIn('trendLongConfirmEntry = strongTrendSupport ? stopBoundedEntry(1, scalpLimitEntry(1, close, trendSupportBasis', source)
        self.assertIn('trendShortConfirmEntry = strongTrendResistance ? stopBoundedEntry(-1, scalpLimitEntry(-1, close, trendResistanceBasis', source)
        self.assertIn('retestCloseEntryOffset = math.max(syminfo.mintick, atr * predictiveEntryOffsetAtr)', source)
        self.assertIn('topFailureRetestEntry = nz(lastTopFailureWatchClose, close) + retestCloseEntryOffset', source)
        self.assertIn('topConfirmEntry = topConfirmedShort ? stopBoundedEntry(-1, topCloseLimitShort ? topConfirmEntryRaw : scalpLimitEntry(-1, close, topBasis', source)
        self.assertIn('bottomFailureRetestEntry = nz(lastBottomFailureWatchClose, close) - retestCloseEntryOffset', source)
        self.assertIn('bottomConfirmEntry = bottomConfirmedLong ? stopBoundedEntry(1, bottomCloseLimitLong ? bottomConfirmEntryRaw : scalpLimitEntry(1, close, bottomBasis', source)
        self.assertIn('selectedTarget = selectedDirection != 0 ? risklib.scalpEmaTarget(selectedDirection, emaFast, atr, emaTargetOffsetAtr)', source)
        self.assertIn('selectedEmaProfitAtr = selectedDirection != 0 and atr > 0.0 ? math.abs(selectedTarget - selectedEntry) / atr : na', source)
        self.assertIn('selectedExpectedRPassed = selectedDirection != 0 and selectedEmaTargetInProfit and selectedEmaProfitAtr >= minEmaProfitAtr and selectedExpectedR >= scalpMinExpectedR', source)
        self.assertIn('selectedTpRunnerGapPassed = selectedDirection != 0 and not na(selectedTpRunnerGapR) and selectedTpRunnerGapR >= minTpRunnerGapR', source)
        self.assertIn('selectedInitialStopClearanceR = selectedDirection == 1 and selectedRiskPerShare > 0.0 ? (low - selectedStop) / selectedRiskPerShare : selectedDirection == -1 and selectedRiskPerShare > 0.0 ? (selectedStop - high) / selectedRiskPerShare : na', source)
        self.assertIn('selectedInitialStopClearanceOk = selectedDirection == 0 or (not na(selectedInitialStopClearanceR) and selectedInitialStopClearanceR >= minInitialStopClearanceR)', source)
        self.assertIn('bool selectedRsiPassed = selectedDirection == 1 ? scalpRsiLongOk : selectedDirection == -1 ? scalpRsiShortOk : false', source)
        self.assertIn('selectedProbeStrictTouchOk = selectedTopProbe ? topStrictRetestTouch : selectedBottomProbe ? bottomStrictRetestTouch : false', source)
        self.assertIn('selectedFailureRetestLimit = selectedTopProbe and topCloseLimitShort or selectedBottomProbe and bottomCloseLimitLong', source)
        self.assertIn('selectedProbeCycleActive = selectedTopProbe ? topProbeCycleActive : selectedBottomProbe ? bottomProbeCycleActive : true', source)
        self.assertIn('selectedProbeCycleConsumed = selectedTopProbe ? topProbeCycleConsumed : selectedBottomProbe ? bottomProbeCycleConsumed : false', source)
        self.assertIn('selectedProbeCyclePassed = not selectedProbeSetup or (selectedProbeCycleActive and not selectedProbeCycleConsumed)', source)
        self.assertIn('selectedEntryNearAnchorOnly = selectedDirection == 0 or selectedProbeStrictTouchOk or selectedFailureRetestLimit or (not na(selectedEntryAnchorDistanceAtr) and selectedEntryAnchorDistanceAtr <= scalpMaxEntryAwayAtr)', source)
        self.assertIn('selectedPlanQualityOk = selectedStructureClear and selectedEntryNearAnchorOnly and selectedProbeCyclePassed and selectedRsiPassed and selectedSmallStopGatePassed and selectedInitialStopClearanceOk and selectedExpectedRPassed and selectedTpRunnerGapPassed', source)
        self.assertIn('selectedBlockReason := "tp_runner_gap_too_small"', source)
        self.assertIn('"probe_cycle_not_active"', source)
        self.assertIn('"probe_cycle_consumed"', source)
        self.assertIn('pendingCancelConsumesProbeCycle = pendingCancelReason == "structure_break_accepted_cancel" or pendingCancelReason == "invalidation_price_breached" or pendingCancelReason == "opposite_confirmed_structure"', source)
        self.assertIn('if pendingCancelConsumesProbeCycle and activeSetup == "probe_2b_top_short"', source)
        self.assertNotIn('if selectedTopProbe and selectedProbeCycleId == topProbeCycleId\n        topProbeCycleConsumed := true', source)
        self.assertIn('selectedPlanValid = selectedDirection != 0 and selectedPlanQualityOk', source)
        self.assertIn('jsonStr("target_role", "ema_fast_scalp_tp")', source)
        self.assertIn('jsonNum("stop_loss", stopPrice)', source)
        self.assertIn('jsonNum("take_profit", targetPrice)', source)
        self.assertIn('jsonNum("ema_fast_price", emaFast)', source)
        self.assertIn('jsonNum("ema_target_price", selectedTarget)', source)
        self.assertIn('jsonNum("rsi", scalpRsi)', source)
        self.assertIn('jsonStr("scalp_cycle_id", selectedScalpCycleId)', source)
        self.assertIn('dailyTotalTrades += 1', source)
        self.assertIn('dailyPnlDollars += pnlDollarsNow', source)
        self.assertIn('activeManualExitReason := "no_follow_scalp_exit"', source)
        self.assertIn('pendingSameDirectionReplace = false', source)
        self.assertIn('orderSlotBusy = pendingEntry or activePosition or hasOpenStrategyPosition', source)
        self.assertIn('submitFreshPlan = confirmed and selectedPlanValid and not orderSlotBusy', source)
        self.assertIn('submitReplacementPlan = false', source)
        self.assertIn('strategy.entry("TV-L", strategy.long, qty=selectedQty, limit=selectedEntry, comment=entryOrderComment', source)
        self.assertIn('strategy.entry("TV-S", strategy.short, qty=selectedQty, limit=selectedEntry, comment=entryOrderComment', source)
        self.assertIn('if not backtestDelayInitialRiskUntilNextBar', source)
        self.assertIn('strategy.exit("TV-L-RISK", from_entry="TV-L", stop=activeStop, limit=activeTarget', source)
        self.assertIn('strategy.exit("TV-S-RISK", from_entry="TV-S", stop=activeStop, limit=activeTarget', source)

    def test_display_explains_event_flow_and_four_plan_lines(self):
        display = self.display_source

        self.assertIn('displayPreset = input.string("核心交易流程", "Display preset"', display)
        self.assertIn('showEntryWindowMarkers = input.bool(true, "Show entry window markers"', display)
        self.assertIn('showFractalMarkers = input.bool(false, "Show fractal markers"', display)
        self.assertIn('showEmaCrossMarkers = input.bool(true, "Show EMA20/50 cross markers"', display)
        self.assertIn('flowLabelTransparency = input.int(45, "Flow label transparency"', display)
        self.assertIn('allowSameBarWeakConfirm = input.bool(false, "Allow same-bar weak confirm"', display)
        self.assertIn('minInitialStopClearanceR = input.float(0.15, "Minimum initial stop clearance (R)"', display)
        self.assertIn('tipVerticalDistanceAtr = input.float(2.0, "Tip vertical distance (x ATR)"', display)
        self.assertIn('labelDetailMode = input.string("compact_tooltip", "Flow label detail mode"', display)
        self.assertIn('eventMarkerMode = input.string("小点tooltip", "Event marker mode"', display)
        self.assertIn('labelTextMode = input.string("auto", "Label text color"', display)
        self.assertIn('flowLabelText(string compactText, string detailText) =>', display)
        self.assertIn('flowLabelTooltip(string detailText) =>', display)
        self.assertIn('flowLabelSize() =>', display)
        self.assertIn('labelStyleForSide(bool above) =>', display)
        self.assertIn('above ? label.style_label_down : label.style_label_up', display)
        self.assertIn('labelYForSide(bool above, float offsetAtr) =>', display)
        self.assertIn('labelAboveForDirection(int direction) =>', display)
        self.assertIn('flowY(int direction, float offsetAtr) =>', display)
        self.assertIn('eventFlowMinOffset(string state) =>', display)
        self.assertIn('eventFlowY(int direction, string state, float offsetAtr) =>', display)
        self.assertIn('profitY(int direction, float offsetAtr) =>', display)
        self.assertIn('profitStyle(int direction) =>', display)
        self.assertIn('drawFlowLabel(int direction, string offsetState, string colorState, string textState, float offsetAtr, string compactText, string detailText) =>', display)
        self.assertIn('drawProfitLabel(int direction, string textState, float offsetAtr, string compactText, string detailText, color labelColor) =>', display)
        self.assertIn('eventMarkerText(string markerText, string detailText) =>', display)
        self.assertIn('eventMarkerTooltip(string detailText) =>', display)
        self.assertIn('eventMarkerSize(string markerKind) =>', display)
        self.assertIn('eventMarkerGlyph(string markerKind, int direction, string markerText) =>', display)
        self.assertIn('eventMarkerColor(string markerKind, int direction) =>', display)
        self.assertIn('eventMarkerStyle(string markerKind, int direction) =>', display)
        self.assertIn('eventMarkerLane(string markerKind) =>', display)
        self.assertIn('eventMarkerY(int direction, string markerKind, float offsetAtr) =>', display)
        self.assertIn('eventMarker(int direction, string markerKind, string markerText, string detailText, float offsetAtr) =>', display)
        self.assertIn('eventMarkerPreserved(string markerKind) =>', display)
        self.assertIn('newEventMarkerLabel(int direction, string markerKind, string markerText, string detailText, float offsetAtr) =>', display)
        self.assertIn('labelYForSide(labelAboveForDirection(direction), math.max(laneOffset, eventFlowMinOffset(markerKind)))', display)
        self.assertIn('labelStyleForSide(labelAboveForDirection(direction))', display)
        self.assertIn('drawFlowLabel(selectedDirection, planVisualState, planVisualState, planVisualState, 1.5, compact, detail)', display)
        self.assertIn('label.new(bar_index, profitY(direction, offsetAtr)', display)
        self.assertIn('style=profitStyle(direction)', display)
        self.assertNotIn('label.new(bar_index, shadowDirection == 1 ? high + atr', display)
        self.assertNotIn('label.new(bar_index, shadowDirection == 1 ? low - atr', display)
        self.assertIn('label.style_none', display)
        self.assertIn('color=color.new(color.white, 100)', display)
        self.assertIn('textcolor=eventMarkerColor(markerKind, direction)', display)
        self.assertNotIn('label.style_circle', display)
        self.assertNotIn('label.style_xcross', display)
        self.assertIn('labelTextColor(string state, int direction) =>', display)
        self.assertIn('pnlDollars(float entryPrice, float levelPrice, int direction, float qty) =>', display)
        self.assertIn('fmtlib.moneyText(', display)
        self.assertIn('risklib.floatingStructureStop(', display)
        self.assertIn('selectedTarget = selectedDirection != 0 ? risklib.scalpEmaTarget(selectedDirection, emaFast, atr, emaTargetOffsetAtr)', display)
        self.assertIn('structureTrailStop = risklib.floatingStructureStop(shadowDirection, shadowStop, lastPivotLow, lastPivotHigh, close, invalidationBuffer)', display)
        self.assertIn('structureCompressStop = risklib.floatingStructureStop(shadowDirection, shadowStop, lastPivotLow, lastPivotHigh, close, invalidationBuffer)', display)
        for line in display.splitlines():
            if "label.new(" in line:
                self.assertTrue("flowLabelText(" in line or "eventMarkerText(" in line)
                self.assertTrue("textcolor=labelTextColor(" in line or "textcolor=eventMarkerColor(" in line)
                self.assertTrue("size=flowLabelSize()" in line or "size=eventMarkerSize(markerKind)" in line)
                self.assertTrue("tooltip=flowLabelTooltip(" in line or "tooltip=eventMarkerTooltip(" in line)
                self.assertNotIn("textcolor=color.white", line)
                self.assertNotIn("size=size.normal", line)
                self.assertNotIn("size=size.small", line)
        self.assertNotIn('Entry window background', display)
        self.assertNotIn('entryWindowShadeColor', display)
        self.assertNotIn('showStatusTable', display)
        self.assertNotIn('showEntryWindowStatus', display)
        self.assertNotIn('tableBgColor', display)
        self.assertNotIn('entryWindowBgColor', display)
        self.assertNotIn('planMoneyText', display)
        self.assertIn('entryWindowStartEvent = showEntryWindowMarkers and useIntradayEntryWindow and inEntryWindow and not inEntryWindow[1]', display)
        self.assertIn('entryWindowEndEvent = showEntryWindowMarkers and useIntradayEntryWindow and not inEntryWindow and inEntryWindow[1]', display)
        self.assertIn('line.new(bar_index, low - atr * 2.0, bar_index, high + atr * 2.0', display)
        self.assertIn('eventMarker(entryWindowOpening ? 1 : -1, "structure", entryWindowBoundaryText, entryWindowBoundaryDetail, 0.78)', display)
        self.assertIn('"交易窗口 OPEN\\n可挂单 "', display)
        self.assertIn('"交易窗口 CLOSED\\n仅观察 "', display)
        self.assertNotIn('ENTRY_WINDOW_MODEL + " / 09:40-15:30"', display)
        self.assertIn('"F" + str.tostring(currentFlowId) + " ②" + intentName(selectedEntryIntent)', display)
        self.assertIn('主因: " + selectedMainReason', display)
        self.assertIn('次因: " + (selectedSecondaryReason == "" ? "none" : selectedSecondaryReason)', display)
        self.assertIn('结构锚点 " + fmtlib.fmt(selectedStructureAnchor)', display)
        self.assertIn('关联流: " + decisionRef + " -> F"', display)
        self.assertIn('fmtlib.reasonCn(', display)
        self.assertIn('volumeJudge = volumeAttackUp ? "放量上攻"', display)
        self.assertIn('showDiagnosticEventFlow = showSignalEventFlow and eventMarkerMode != "关闭"', display)
        self.assertIn('eventMarkersVisible = showSignalEventFlow and eventMarkerMode == "小点tooltip"', display)
        self.assertIn('diagnosticLabelsVisible = flowLabelsVisible and eventMarkerMode == "大标签调试"', display)
        self.assertIn('eventMarkerPriority(string markerKind) =>', display)
        self.assertIn('markerKind == "structure" or markerKind == "watch"', display)
        self.assertIn('topMarkerPriority', display)
        self.assertIn('bottomMarkerPriority', display)
        self.assertIn('label.delete(topMarkerLabel)', display)
        self.assertIn('label.delete(bottomMarkerLabel)', display)
        self.assertIn('drawDiagnosticEvent(int direction, string markerKind', display)
        self.assertIn('drawDiagnosticEvent(acceptedDirection, "structure"', display)
        self.assertIn('drawDiagnosticEvent(selectedDirection, blockedMarkerKind', display)
        self.assertIn('"entry_far_limit_wait"', display)
        self.assertIn('"weak_next_x"', display)
        self.assertIn('"weak_structure_reversal"', display)
        self.assertIn('"trend_blocked"', display)
        self.assertIn('eventMarker(selectedDirection, selectedCloseFarFromAnchor ? "entry_far_limit_wait" : "confirmed"', display)
        self.assertIn('drawDiagnosticEvent(distributionDirection, distributionMarkerKind', display)
        self.assertIn('drawDiagnosticEvent(-1, climaxMarkerKind', display)
        self.assertIn('drawDiagnosticEvent(touchDirection, "observe"', display)
        self.assertIn('drawDiagnosticEvent(attackDirection, "watch"', display)
        self.assertIn('plot(showEmaFastSlowLines ? emaFast : na, "EMA 20 快线"', display)
        self.assertIn('plot(showDtpTrendLine ? dtpAvg : na, "DTP 趋势线", color=dtpLineColor, linewidth=2)', display)
        self.assertIn('plot(showBandLines ? sdUpper : na, "SD signal upper"', display)
        self.assertIn('plot(showStructureGuideLines ? todayStructHigh : na, "Today Struct High"', display)
        self.assertIn('plot(showStructureGuideLines ? todayStructLow : na, "Today Struct Low"', display)
        self.assertIn('plot(showStructureGuideLines ? todayStructHighZoneHigh : na, "Struct High Zone High"', display)
        self.assertIn('plot(showStructureGuideLines ? todayStructLowZoneLow : na, "Struct Low Zone Low"', display)
        self.assertIn('selectedProbeRetestGapBars', display)
        self.assertIn('selectedProbeLeftLegBps', display)
        self.assertIn('selectedProbeMiddleRatio', display)
        self.assertIn('selectedProbeRightRatio', display)
        self.assertIn('selectedStructureGateReason', display)
        self.assertIn('selectedStructureGateFlags', display)
        self.assertIn('selectedNakedReversalCandidate', display)
        self.assertIn('selectedVolumeReason', display)
        self.assertIn('selectedVolumeRatio', display)
        self.assertIn('量能 vol/MA " + fmtlib.fmt(selectedVolumeRatio)', display)
        self.assertIn('selectedLevelRole', display)
        self.assertIn('selectedAttackVolumeCooling', display)
        self.assertIn('位置角色 " + selectedLevelRole', display)
        self.assertIn('exhaustionWatchTop', display)
        self.assertIn('前高二测：多单止盈区，等待确认做空', display)
        self.assertIn('衰竭保护', display)
        self.assertIn('structureBreakAcceptedEvent', display)
        self.assertIn('站稳前高：更新今日结构高', display)
        self.assertIn('structureBreakExtendedEvent', display)
        self.assertIn('前高延伸：结构高跟随最新日内高点', display)
        self.assertIn('liveHighStateEvent', display)
        self.assertIn('结构高首次确认', display)
        self.assertIn('前高确认为结构高', display)
        self.assertIn('结构高抬高', display)
        self.assertIn('旧结构 " + oldStructureText + " -> 新结构 "', display)
        self.assertIn('触发原因: " + triggerReason', display)
        self.assertIn('当前K是否" + (highSideEvent ? "新高" : "新低")', display)
        self.assertIn('说明: 这是结构锚点更新，不是开仓信号', display)
        self.assertIn('前高回落确认', display)
        self.assertIn('同一结构簇新高', display)
        self.assertIn('候选结构高', display)
        self.assertIn('冻结突破基准', display)
        self.assertNotIn('volumeBlockedTop', display)
        self.assertNotIn('volumeBlockedBottom', display)
        self.assertNotIn('②冷却中', display)
        self.assertNotIn('放量攻击后仍在冷却', display)
        self.assertIn('裸K放量上攻观察 空', display)
        self.assertIn('不挂单，等放量失败或衰弱破位', display)
        self.assertIn('volumeClimaxTopWatchEvent', display)
        self.assertIn('topDecisionSeq', display)
        self.assertIn('裸K放量上攻观察 空', display)
        self.assertIn('高位放量K是攻击锚点', display)
        self.assertIn('等放量失败或衰弱破位', display)
        self.assertIn('volumeClimaxTopConfirmEvent', display)
        self.assertIn('volumeClimaxTopConfirmRaw', display)
        self.assertIn('volumeClimaxTopConfirmEvent = volumeClimaxTopConfirmRaw and not volumeClimaxTopConfirmRaw[1]', display)
        self.assertIn('visualSlotBusy = shadowPending or shadowOpen or shadowReleasedThisBar', display)
        self.assertIn('shadowProbeCycleId := selectedProbeSetup ? selectedProbeCycleId : na', display)
        self.assertIn('selectedPlanQualityOk = selectedStructureClear and selectedEntryNearAnchorOnly and selectedProbeCyclePassed and selectedRsiPassed', display)
        self.assertIn('selectedInitialStopClearanceOk', display)
        self.assertIn('same_bar_weak_confirm_disabled', display)
        self.assertIn('entry_stop_clearance_too_small', display)
        self.assertIn('selectedEntryNearAnchorOnly = selectedDirection == 0 or selectedProbeStrictTouchOk or selectedFailureRetestLimit or (not na(selectedEntryAnchorDistanceAtr) and selectedEntryAnchorDistanceAtr <= scalpMaxEntryAwayAtr)', display)
        self.assertIn('probe_cycle_not_active', display)
        self.assertIn('probe_cycle_consumed', display)
        self.assertIn('探针周期: id " + str.tostring(selectedProbeCycleId)', display)
        self.assertIn('失败回抽限价只决定挂单价，不绕过重新触及周期', display)
        self.assertIn('failureRetestLimit=true -> 允许失败回抽限价入场', display)
        self.assertIn('未触及限价: " + touchText', display)
        self.assertIn('cancelConsumesProbeCycle = pendingInvalidated', display)
        self.assertIn('确认但未新开', display)
        self.assertIn('mainPlanWillDraw = confirmed and showSignalEventFlow and selectedPlanValid and not visualSlotBusy', display)
        self.assertIn('canEvaluateShadowExit = confirmed and shadowOpen and not na(shadowEntryBar) and (allowSameBarRunnerAfterFill or bar_index > shadowEntryBar)', display)
        self.assertIn('shadowReleasedBar := bar_index', display)
        self.assertIn('mainPlanStatusText(bool childAllowed, bool selectedByMain, bool planCreatedNow, string childReason) =>', display)
        self.assertIn('planGateDetailText(bool childAllowed, bool selectedByMain, bool planCreatedNow, string childReason) =>', display)
        self.assertIn('刚退出/刚撤销，本K不再开新plan', display)
        self.assertIn('主流程未挂单', display)
        self.assertIn('已生成plan', display)
        self.assertIn('子条件: 通过 / passed', display)
        self.assertIn('selectedPlanValid: " + str.tostring(selectedPlanValid)', display)
        self.assertIn('③放量失败确认 空', display)
        self.assertIn('候选确认 空', display)
        self.assertIn('红K收回攻击K实体中位', display)
        self.assertIn('红K跌破攻击K低点', display)
        self.assertIn('SL 前高+buffer', display)
        self.assertIn('成交量判断:', display)
        self.assertIn('确认但过滤', display)
        self.assertIn('过滤原因:', display)
        self.assertIn('可挂单', display)
        self.assertIn('weakNewTopWatchEvent', display)
        self.assertIn('弱新高观察 空', display)
        self.assertIn('新高缩量', display)
        self.assertIn('等待弱收确认', display)
        self.assertIn('weakNewBottomWatchEvent', display)
        self.assertIn('弱新低观察 多', display)
        self.assertIn('新低缩量', display)
        self.assertIn('等待强收确认', display)
        self.assertIn('nakedQuietWatchEvent', display)
        self.assertIn('新高/前高观察 空', display)
        self.assertIn('高位衰弱/打压观察 空', display)
        self.assertIn('新低/前低观察 多', display)
        self.assertIn('低位衰弱/打压观察 多', display)
        self.assertIn('等待红K跌破观察簇低点', display)
        self.assertIn('等待绿K突破观察簇高点', display)
        self.assertIn('distributionConfirmEvent', display)
        self.assertIn('topDistributionOrDropConfirmed', display)
        self.assertIn('topImmediateReversalShort', display)
        self.assertIn('topFailureRepeatShort', display)
        self.assertIn('topConfirmGapOk', display)
        self.assertIn('selectedFailureReentry', display)
        self.assertIn('bottomAccumulationOrRiseConfirmed', display)
        self.assertIn('topHighVolumeDropConfirmed', display)
        self.assertIn('bottomHighVolumeRiseConfirmed', display)
        self.assertIn('topNoDemandBreakConfirmed', display)
        self.assertIn('bottomNoSupplyBreakConfirmed', display)
        self.assertIn('same_bar_weak_confirm', display)
        self.assertIn('第一根弱K已确认，不再等下一根', display)
        self.assertIn('只有下次再次触碰高点/低点才允许挂单', display)
        self.assertIn('weakWatchDirectionForNext', display)
        self.assertIn('pendingNoFillDetail(int direction, float entryPrice, int signalBar, int expiresBar) =>', display)
        self.assertIn('weakNextDetailText(int direction, string source', display)
        self.assertIn('weakNextReason(bool retestOk, bool watchBreakOk, bool rsiOk, bool distanceOk, bool finalFiltered) =>', display)
        self.assertIn('pendingNextNoFill', display)
        self.assertIn('"X " + dirName(direction) + "·限价未成交"', display)
        self.assertIn('"short fill 条件: high >= entry"', display)
        self.assertIn('"long fill 条件: low <= entry"', display)
        self.assertIn('"X " + dirName(direction) + "·弱信号未生效"', display)
        self.assertIn('"\\n本根未触发: " + fmtlib.reasonCn(why)', display)
        self.assertIn('"\\n触达结构: " + str.tostring(retestOk)', display)
        self.assertIn('"\\n破观察位: " + str.tostring(watchBreakOk)', display)
        self.assertIn('"\\nRSI证明: " + str.tostring(rsiOk)', display)
        self.assertIn('"\\n结论: 只观察，不挂单"', display)
        self.assertIn('weakWatchForNext', display)
        self.assertIn('weakTopQuietForNext', display)
        self.assertIn('weakBottomQuietForNext', display)
        self.assertIn('weakTopAwayForNext', display)
        self.assertIn('weakBottomAwayForNext', display)
        self.assertIn('weakTopNewForNext', display)
        self.assertIn('weakBottomNewForNext', display)
        self.assertIn('weak_next_no_retest', display)
        self.assertIn('weak_next_no_break_watch', display)
        self.assertIn('weak_next_rsi_missing', display)
        self.assertIn('weak_next_distance_too_far', display)
        self.assertIn('weak_next_filtered', display)
        self.assertIn('pending_limit_not_touched', display)
        self.assertIn('高低点K收盘价±offset', display)
        self.assertIn('③放量失败确认 空', display)
        self.assertIn('distributionConfirmRaw', display)
        self.assertIn('distributionConfirmEvent = distributionConfirmRaw and not distributionConfirmRaw[1]', display)
        self.assertNotIn('④确认挂空', display)
        self.assertNotIn('④确认挂多', display)
        self.assertIn('裸K放量失败确认', display)
        self.assertIn('裸K高位失败确认', display)
        self.assertIn('③高位失败确认 空', display)
        self.assertIn('冲高大回落/高位失败', display)
        self.assertIn('回抽限价 entry', display)
        self.assertIn('naked_high_immediate_reversal', display)
        self.assertIn('naked_high_immediate_reversal_confirmed', display)
        self.assertIn('高位放量失败', display)
        self.assertIn('③跌破观察簇确认 空', display)
        self.assertIn('候选确认 空', display)
        self.assertIn('连续衰弱/打压', display)
        self.assertIn('③放量失败确认 多', display)
        self.assertIn('候选确认 多', display)
        self.assertIn('裸K连续衰弱确认', display)
        self.assertIn('低位放量失败', display)
        self.assertIn('③突破观察簇确认 多', display)
        self.assertIn('候选确认 多', display)
        self.assertIn('连续衰弱/打压', display)
        self.assertIn('distributionSlText = distributionDirection == -1 ? "前高+buffer "', display)
        self.assertIn('distributionDetail := distributionDetail + "\\nSL " + distributionSlText', display)
        self.assertIn('naked_high_volume_reversal_confirmed', display)
        self.assertIn('naked_low_volume_reversal_confirmed', display)
        self.assertIn('naked_high_decay_break_confirmed', display)
        self.assertIn('naked_low_decay_break_confirmed', display)
        self.assertIn('unconfirmedTopWatch', display)
        self.assertIn('未确认，不挂单', display)
        self.assertIn('只有 confirmed_limit 才会画 plan 并联动 Core/IBKR', display)
        self.assertIn('连续衰减 " + fmtlib.fmt(topWatch ? topDecayStreak * 1.0 : bottomDecayStreak * 1.0)', display)
        self.assertIn('"\\n三段结构 L" + fmtlib.fmt(selectedProbeLeftLegBps)', display)
        self.assertIn('"\\n结构清晰: " + str.tostring(selectedStructureClear)', display)
        self.assertIn('"\\n价格行为条件: " + selectedStructureGateFlags', display)
        self.assertIn('"\\nclose已走远：只挂回抽限价，不追价"', display)
        self.assertIn('裸K反转已触发候选，但价格行为结构未通过，所以不挂单', display)
        self.assertIn('str.tostring(maxRetestAfterMiddleSwingBars)', display)
        self.assertIn('同向距离 " + fmtlib.fmt(selectedSameSideSignalDistanceAtr)', display)
        self.assertIn('plotshape(showComponentMarkers and sdLowerHit, "SD lower hit"', display)
        self.assertIn('plotshape(showAnyFractalMarkers and fractalBull, "Fractal bull"', display)
        self.assertIn('showAnyEmaCrossMarkers = showEmaCrossMarkers or displayIndicatorMode or displayDebugMode', display)
        self.assertIn('plotshape(showAnyEmaCrossMarkers and emaGoldenCross, "EMA20/50 golden cross"', display)
        self.assertIn('plotshape(showComponentMarkers and bullDivNow, "Bull divergence"', display)
        self.assertIn('newPlanLevelLine(float level, int lineEnd, color lineColor) =>', display)
        self.assertIn('rollPlanLevelLine(line lineId, float previousLevel, float currentLevel, int lineEnd, color lineColor) =>', display)
        self.assertIn('line.set_y1(lineId, level)', display)
        self.assertIn('line.set_y2(lineId, level)', display)
        self.assertIn('line.set_y1(lineId, previousLevel)', display)
        self.assertIn('line.set_y2(lineId, previousLevel)', display)
        self.assertIn('line.new(bar_index, level, lineEnd, level, color=lineColor, width=2)', display)
        self.assertIn('currentEntryLine := newPlanLevelLine(shadowEntry', display)
        self.assertIn('newPlanLevelLine(shadowEntry, lineEnd, color.new(color.yellow, 0))', display)
        self.assertIn('currentStopLine := newPlanLevelLine(shadowStop', display)
        self.assertIn('newPlanLevelLine(shadowStop, lineEnd, color.new(color.red, 0))', display)
        self.assertIn('currentRunnerLine := newPlanLevelLine(shadowRunner', display)
        self.assertIn('newPlanLevelLine(shadowRunner, lineEnd, color.new(color.blue, 0))', display)
        self.assertIn('currentTargetLine := newPlanLevelLine(shadowTarget', display)
        self.assertIn('newPlanLevelLine(shadowTarget, lineEnd, color.new(color.green, 0))', display)
        self.assertIn('currentStopLine := rollPlanLevelLine(currentStopLine, currentStopLineLevel, shadowStop', display)
        self.assertIn('currentTargetLine := rollPlanLevelLine(currentTargetLine, currentTargetLineLevel, shadowTarget', display)
        self.assertNotIn('line.set_y2(currentStopLine, shadowStop)', display)
        self.assertIn('plotshape(newPlanNow and selectedDirection == 1, title="Predictive/confirmed long", style=shape.triangleup, location=location.belowbar, color=color.new(color.green, 35), size=size.tiny, text="")', display)
        self.assertIn('plotshape(newPlanNow and selectedDirection == -1, title="Predictive/confirmed short", style=shape.triangledown, location=location.abovebar, color=color.new(color.red, 35), size=size.tiny, text="")', display)
        self.assertNotIn('var label currentEntryLabel = na', display)
        self.assertNotIn('var label currentStopLabel = na', display)
        self.assertNotIn('var label currentRunnerLabel = na', display)
        self.assertNotIn('var label currentTargetLabel = na', display)
        self.assertNotIn('currentEntryLabel := label.new(lineEnd, shadowEntry', display)
        self.assertNotIn('currentStopLabel := label.new(lineEnd, shadowStop', display)
        self.assertNotIn('currentRunnerLabel := label.new(lineEnd, shadowRunner', display)
        self.assertNotIn('currentTargetLabel := label.new(lineEnd, shadowTarget', display)
        self.assertNotIn('label.set_text(currentStopLabel', display)
        self.assertIn('fmtlib.moneyText(pnlDollars(selectedEntry, selectedStop, selectedDirection, selectedQty))', display)
        self.assertNotIn('"金额"', display)
        self.assertNotIn('"黄/红/蓝/绿"', display)
        self.assertNotIn('"Entry / SL / 0.6R / EMA20TP"', display)


if __name__ == "__main__":
    unittest.main()
