apiVersion: 1

policies:
  - orgId: 1
    receiver: feishu-existing-alert-bot
    group_by:
      - grafana_folder
      - alertname
      - severity
      - service
      - environment
      - job
      - instance
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
