from __future__ import annotations

from ibkr_compute.api.compute.pipeline_views import build_compute_response
from ibkr_compute.api.compute.request import (
    get_requested_environments,
    get_requested_symbols,
    is_environment_compute_enabled,
    should_persist_compute_signals,
)
from ibkr_compute.api.compute.runtime_ops import (
    _get_runtime_status_snapshot,
    _run_internal_compute,
    _run_internal_scan,
    build_recompute_response,
    build_scan_response,
)
from ibkr_compute.api.compute.support import (
    apply_cursor_map,
    bootstrap_engine_state,
    build_compute_cursor_key,
    build_indicator_payload,
    build_signal_payload,
    collect_environment_cursor_map,
    ensure_higher_timeframe_bars,
    fetch_interval_bars,
    flush_indicator_batch,
    flush_signal_batch,
    get_active_trade_symbols,
    get_daily_change_fields,
    get_fetch_since_ms,
    get_market_monitor_symbols,
    get_or_create_engine,
    get_signal_generator_params,
    has_interval_bars,
    is_recent_signal_bar,
    load_persisted_compute_cursors,
    materialize_engines_from_storage,
    parse_compute_cursor_key,
    persist_compute_cursors,
    rebuild_higher_timeframe_bars,
    refresh_daily_close_cache,
    refresh_symbol_metadata,
    repair_symbol_pipeline_from_storage,
    reset_compute_state_for_symbols,
    reset_daily_runtime_state,
    seed_compute_cursors_from_indicators,
)


COMPUTE_EXPORTS = {
    "apply_cursor_map": apply_cursor_map,
    "bootstrap_engine_state": bootstrap_engine_state,
    "build_compute_cursor_key": build_compute_cursor_key,
    "build_compute_response": build_compute_response,
    "build_indicator_payload": build_indicator_payload,
    "build_recompute_response": build_recompute_response,
    "build_scan_response": build_scan_response,
    "build_signal_payload": build_signal_payload,
    "collect_environment_cursor_map": collect_environment_cursor_map,
    "ensure_higher_timeframe_bars": ensure_higher_timeframe_bars,
    "fetch_interval_bars": fetch_interval_bars,
    "flush_indicator_batch": flush_indicator_batch,
    "flush_signal_batch": flush_signal_batch,
    "get_active_trade_symbols": get_active_trade_symbols,
    "get_daily_change_fields": get_daily_change_fields,
    "get_fetch_since_ms": get_fetch_since_ms,
    "get_market_monitor_symbols": get_market_monitor_symbols,
    "get_or_create_engine": get_or_create_engine,
    "get_requested_environments": get_requested_environments,
    "get_requested_symbols": get_requested_symbols,
    "get_signal_generator_params": get_signal_generator_params,
    "has_interval_bars": has_interval_bars,
    "is_environment_compute_enabled": is_environment_compute_enabled,
    "is_recent_signal_bar": is_recent_signal_bar,
    "load_persisted_compute_cursors": load_persisted_compute_cursors,
    "materialize_engines_from_storage": materialize_engines_from_storage,
    "parse_compute_cursor_key": parse_compute_cursor_key,
    "persist_compute_cursors": persist_compute_cursors,
    "refresh_daily_close_cache": refresh_daily_close_cache,
    "refresh_symbol_metadata": refresh_symbol_metadata,
    "repair_symbol_pipeline_from_storage": repair_symbol_pipeline_from_storage,
    "reset_compute_state_for_symbols": reset_compute_state_for_symbols,
    "reset_daily_runtime_state": reset_daily_runtime_state,
    "seed_compute_cursors_from_indicators": seed_compute_cursors_from_indicators,
    "should_persist_compute_signals": should_persist_compute_signals,
    "_get_runtime_status_snapshot": _get_runtime_status_snapshot,
    "_run_internal_compute": _run_internal_compute,
    "_run_internal_scan": _run_internal_scan,
}
